// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: spell/service.proto

package spell

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CorrectionLevel int32

const (
	CorrectionLevel_LEVEL_UNSPECIFIED CorrectionLevel = 0
	CorrectionLevel_LEVEL_ERROR       CorrectionLevel = 1
	CorrectionLevel_LEVEL_SUGGESTION  CorrectionLevel = 2
)

// Enum value maps for CorrectionLevel.
var (
	CorrectionLevel_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_ERROR",
		2: "LEVEL_SUGGESTION",
	}
	CorrectionLevel_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_ERROR":       1,
		"LEVEL_SUGGESTION":  2,
	}
)

func (x CorrectionLevel) Enum() *CorrectionLevel {
	p := new(CorrectionLevel)
	*p = x
	return p
}

func (x CorrectionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CorrectionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_spell_service_proto_enumTypes[0].Descriptor()
}

func (CorrectionLevel) Type() protoreflect.EnumType {
	return &file_spell_service_proto_enumTypes[0]
}

func (x CorrectionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CorrectionLevel.Descriptor instead.
func (CorrectionLevel) EnumDescriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{0}
}

type SupportedLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedLanguagesRequest) Reset() {
	*x = SupportedLanguagesRequest{}
	mi := &file_spell_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedLanguagesRequest) ProtoMessage() {}

func (x *SupportedLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedLanguagesRequest.ProtoReflect.Descriptor instead.
func (*SupportedLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{0}
}

type SupportedLanguagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Languages that can be used for spellchecking.
	Languages     []*Language `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupportedLanguagesResponse) Reset() {
	*x = SupportedLanguagesResponse{}
	mi := &file_spell_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupportedLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportedLanguagesResponse) ProtoMessage() {}

func (x *SupportedLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportedLanguagesResponse.ProtoReflect.Descriptor instead.
func (*SupportedLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{1}
}

func (x *SupportedLanguagesResponse) GetLanguages() []*Language {
	if x != nil {
		return x.Languages
	}
	return nil
}

type Language struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Code for the language.
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Language) Reset() {
	*x = Language{}
	mi := &file_spell_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Language) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Language) ProtoMessage() {}

func (x *Language) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Language.ProtoReflect.Descriptor instead.
func (*Language) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{2}
}

func (x *Language) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type TextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text to spellcheck.
	Text []string `protobuf:"bytes,1,rep,name=text,proto3" json:"text,omitempty"`
	// Language to check the text for.
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// Suggestions enables generation of suggestions for misspelled words. In
	// interactive applications this should normally be done by calling the
	// Suggestions method on demand.
	Suggestions bool `protobuf:"varint,3,opt,name=suggestions,proto3" json:"suggestions,omitempty"`
	// CustomOnly limits checks to the custom dictionary and rules, skipping the
	// hunspell pass. Useful when you only want to surface custom corrections
	// without the noise of hunspell results.
	CustomOnly    bool `protobuf:"varint,4,opt,name=custom_only,json=customOnly,proto3" json:"custom_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_spell_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{3}
}

func (x *TextRequest) GetText() []string {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *TextRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TextRequest) GetSuggestions() bool {
	if x != nil {
		return x.Suggestions
	}
	return false
}

func (x *TextRequest) GetCustomOnly() bool {
	if x != nil {
		return x.CustomOnly
	}
	return false
}

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Misspelled    []*Misspelled          `protobuf:"bytes,1,rep,name=misspelled,proto3" json:"misspelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_spell_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{4}
}

func (x *TextResponse) GetMisspelled() []*Misspelled {
	if x != nil {
		return x.Misspelled
	}
	return nil
}

type Misspelled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MisspelledEntry     `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Misspelled) Reset() {
	*x = Misspelled{}
	mi := &file_spell_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Misspelled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Misspelled) ProtoMessage() {}

func (x *Misspelled) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Misspelled.ProtoReflect.Descriptor instead.
func (*Misspelled) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{5}
}

func (x *Misspelled) GetEntries() []*MisspelledEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MisspelledEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text that was used in the source text.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Suggestions for replacements.
	Suggestions []*Suggestion `protobuf:"bytes,2,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	// Level is the level of the correction.
	Level CorrectionLevel `protobuf:"varint,3,opt,name=level,proto3,enum=elephant.spell.CorrectionLevel" json:"level,omitempty"`
	// Status of the custom entry the correction is based on, e.g. "accepted" or
	// "pending". Empty for corrections that don't originate from a custom entry
	// (such as plain hunspell results). Clients can use this to indicate that a
	// correction comes from an unreviewed (pending) entry.
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Spans are the character ranges in the source text where this specific
	// correction applies. The same text can occur several times with different
	// outcomes (e.g. only one occurrence is corrected), so clients should act on
	// these ranges rather than searching for the text. Empty for corrections that
	// apply wherever the text appears, such as plain hunspell results.
	Spans         []*TextSpan `protobuf:"bytes,5,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MisspelledEntry) Reset() {
	*x = MisspelledEntry{}
	mi := &file_spell_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MisspelledEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MisspelledEntry) ProtoMessage() {}

func (x *MisspelledEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MisspelledEntry.ProtoReflect.Descriptor instead.
func (*MisspelledEntry) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{6}
}

func (x *MisspelledEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MisspelledEntry) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *MisspelledEntry) GetLevel() CorrectionLevel {
	if x != nil {
		return x.Level
	}
	return CorrectionLevel_LEVEL_UNSPECIFIED
}

func (x *MisspelledEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MisspelledEntry) GetSpans() []*TextSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

// TextSpan is a half-open range [start, end) into a source text, counted in
// Unicode characters (code points / runes), not bytes. For text within the
// Basic Multilingual Plane this matches JavaScript/UTF-16 string offsets.
type TextSpan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Start is the character offset of the match in the source text.
	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	// End is the character offset just past the match.
	End           int64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextSpan) Reset() {
	*x = TextSpan{}
	mi := &file_spell_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSpan) ProtoMessage() {}

func (x *TextSpan) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSpan.ProtoReflect.Descriptor instead.
func (*TextSpan) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{7}
}

func (x *TextSpan) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TextSpan) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type SuggestionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Text is the word or phrase to get suggestions for.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Language to get suggestions in.
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	// CustomOnly limits suggestions to the custom dictionary and rules, skipping
	// the hunspell pass.
	CustomOnly    bool `protobuf:"varint,3,opt,name=custom_only,json=customOnly,proto3" json:"custom_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsRequest) Reset() {
	*x = SuggestionsRequest{}
	mi := &file_spell_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsRequest) ProtoMessage() {}

func (x *SuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionsRequest.ProtoReflect.Descriptor instead.
func (*SuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{8}
}

func (x *SuggestionsRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SuggestionsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SuggestionsRequest) GetCustomOnly() bool {
	if x != nil {
		return x.CustomOnly
	}
	return false
}

type SuggestionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Suggestions for replacements.
	Suggestions   []*Suggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsResponse) Reset() {
	*x = SuggestionsResponse{}
	mi := &file_spell_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsResponse) ProtoMessage() {}

func (x *SuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionsResponse.ProtoReflect.Descriptor instead.
func (*SuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{9}
}

func (x *SuggestionsResponse) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type Suggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_spell_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{10}
}

func (x *Suggestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Suggestion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language to list entries for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Page to return.
	Page int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Query filters entries by a free-text substring, matched against the entry
	// text, its description, and its common mistakes.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// Status to filter entries by
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// PageSize is the number of entries to return per page. Optional, defaults to
	// 100 when zero.
	PageSize      int64 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_spell_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListEntriesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListEntriesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEntriesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListEntriesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListEntriesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*CustomEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_spell_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListEntriesResponse) GetEntries() []*CustomEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CustomEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language the entry is for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Text is the word (or phrase) itself.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Status of the entry, this is used for moderation.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Description of the entry.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// CommonMistakes are misspellings or alternative spellings that should be
	// flagged and corrected to the entry text. Supports {A|B} expansion.
	CommonMistakes []string `protobuf:"bytes,5,rep,name=common_mistakes,json=commonMistakes,proto3" json:"common_mistakes,omitempty"`
	// Level to use when offering corrections based on this entry. Optional,
	// defaults to LEVEL_ERROR.
	Level CorrectionLevel `protobuf:"varint,6,opt,name=level,proto3,enum=elephant.spell.CorrectionLevel" json:"level,omitempty"`
	// Forms is an alternative to the common mistakes -> text pairing and allows
	// the mapping of different forms of the word or phrase to specific
	// replacements.
	Forms map[string]string `protobuf:"bytes,7,rep,name=forms,proto3" json:"forms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Updated is the last update time in RFC3339 format.
	Updated string `protobuf:"bytes,8,opt,name=updated,proto3" json:"updated,omitempty"`
	// UpdatedBy is the identity of the party that last updated the entry.
	UpdatedBy string `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// CaseSensitive controls whether the entry matches only with the exact casing
	// of its text and common mistakes. Defaults to false (case-insensitive
	// matching), which suits ordinary words. Enable it for proper nouns; a
	// case-sensitive entry additionally flags leading-letter miscasings of its
	// text and common mistakes (e.g. "mexico city") and suggests the exact
	// casing.
	CaseSensitive bool `protobuf:"varint,10,opt,name=case_sensitive,json=caseSensitive,proto3" json:"case_sensitive,omitempty"`
	// Before, when set, only flags a match when immediately preceded by one of
	// these words.
	Before []string `protobuf:"bytes,11,rep,name=before,proto3" json:"before,omitempty"`
	// After, when set, only flags a match when immediately followed by one of
	// these words.
	After []string `protobuf:"bytes,12,rep,name=after,proto3" json:"after,omitempty"`
	// NotBefore suppresses the match when preceded by one of these words.
	NotBefore []string `protobuf:"bytes,13,rep,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	// NotAfter suppresses the match when followed by one of these words.
	NotAfter      []string `protobuf:"bytes,14,rep,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomEntry) Reset() {
	*x = CustomEntry{}
	mi := &file_spell_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomEntry) ProtoMessage() {}

func (x *CustomEntry) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomEntry.ProtoReflect.Descriptor instead.
func (*CustomEntry) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{13}
}

func (x *CustomEntry) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CustomEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CustomEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CustomEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CustomEntry) GetCommonMistakes() []string {
	if x != nil {
		return x.CommonMistakes
	}
	return nil
}

func (x *CustomEntry) GetLevel() CorrectionLevel {
	if x != nil {
		return x.Level
	}
	return CorrectionLevel_LEVEL_UNSPECIFIED
}

func (x *CustomEntry) GetForms() map[string]string {
	if x != nil {
		return x.Forms
	}
	return nil
}

func (x *CustomEntry) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *CustomEntry) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *CustomEntry) GetCaseSensitive() bool {
	if x != nil {
		return x.CaseSensitive
	}
	return false
}

func (x *CustomEntry) GetBefore() []string {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *CustomEntry) GetAfter() []string {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *CustomEntry) GetNotBefore() []string {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *CustomEntry) GetNotAfter() []string {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

type ListDictionariesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictionariesRequest) Reset() {
	*x = ListDictionariesRequest{}
	mi := &file_spell_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictionariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionariesRequest) ProtoMessage() {}

func (x *ListDictionariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionariesRequest.ProtoReflect.Descriptor instead.
func (*ListDictionariesRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{14}
}

type ListDictionariesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dictionaries  []*CustomDictionary    `protobuf:"bytes,1,rep,name=dictionaries,proto3" json:"dictionaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictionariesResponse) Reset() {
	*x = ListDictionariesResponse{}
	mi := &file_spell_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictionariesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictionariesResponse) ProtoMessage() {}

func (x *ListDictionariesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictionariesResponse.ProtoReflect.Descriptor instead.
func (*ListDictionariesResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListDictionariesResponse) GetDictionaries() []*CustomDictionary {
	if x != nil {
		return x.Dictionaries
	}
	return nil
}

type CustomDictionary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language the dictionary is for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// EntryCount for the dictionary.
	EntryCount int64 `protobuf:"varint,2,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	// PendingCount is the number of entries awaiting moderation.
	PendingCount int64 `protobuf:"varint,3,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	// RuleCount is the number of pattern rules for the language.
	RuleCount int64 `protobuf:"varint,4,opt,name=rule_count,json=ruleCount,proto3" json:"rule_count,omitempty"`
	// RulePendingCount is the number of rules awaiting moderation.
	RulePendingCount int64 `protobuf:"varint,5,opt,name=rule_pending_count,json=rulePendingCount,proto3" json:"rule_pending_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CustomDictionary) Reset() {
	*x = CustomDictionary{}
	mi := &file_spell_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomDictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomDictionary) ProtoMessage() {}

func (x *CustomDictionary) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomDictionary.ProtoReflect.Descriptor instead.
func (*CustomDictionary) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{16}
}

func (x *CustomDictionary) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CustomDictionary) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *CustomDictionary) GetPendingCount() int64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

func (x *CustomDictionary) GetRuleCount() int64 {
	if x != nil {
		return x.RuleCount
	}
	return 0
}

func (x *CustomDictionary) GetRulePendingCount() int64 {
	if x != nil {
		return x.RulePendingCount
	}
	return 0
}

type GetEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language the entry is for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Text is the word or phrase to get the entry for.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_spell_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetEntryRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetEntryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetEntryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entry information.
	Entry         *CustomEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryResponse) Reset() {
	*x = GetEntryResponse{}
	mi := &file_spell_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryResponse) ProtoMessage() {}

func (x *GetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryResponse.ProtoReflect.Descriptor instead.
func (*GetEntryResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetEntryResponse) GetEntry() *CustomEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type SetEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Entry to set.
	Entry         *CustomEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEntryRequest) Reset() {
	*x = SetEntryRequest{}
	mi := &file_spell_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryRequest) ProtoMessage() {}

func (x *SetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryRequest.ProtoReflect.Descriptor instead.
func (*SetEntryRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{19}
}

func (x *SetEntryRequest) GetEntry() *CustomEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type SetEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEntryResponse) Reset() {
	*x = SetEntryResponse{}
	mi := &file_spell_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryResponse) ProtoMessage() {}

func (x *SetEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryResponse.ProtoReflect.Descriptor instead.
func (*SetEntryResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{20}
}

type SetEntryStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language the entry is for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Text is the word or phrase to update.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// Status to set, e.g. "accepted" or "pending".
	Status        string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEntryStatusRequest) Reset() {
	*x = SetEntryStatusRequest{}
	mi := &file_spell_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEntryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryStatusRequest) ProtoMessage() {}

func (x *SetEntryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryStatusRequest.ProtoReflect.Descriptor instead.
func (*SetEntryStatusRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{21}
}

func (x *SetEntryStatusRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SetEntryStatusRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SetEntryStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetEntryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEntryStatusResponse) Reset() {
	*x = SetEntryStatusResponse{}
	mi := &file_spell_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEntryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEntryStatusResponse) ProtoMessage() {}

func (x *SetEntryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEntryStatusResponse.ProtoReflect.Descriptor instead.
func (*SetEntryStatusResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{22}
}

type DeleteEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language the entry is for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Text is the word or phrase to delete.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryRequest) Reset() {
	*x = DeleteEntryRequest{}
	mi := &file_spell_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryRequest) ProtoMessage() {}

func (x *DeleteEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteEntryRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteEntryRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DeleteEntryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type DeleteEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEntryResponse) Reset() {
	*x = DeleteEntryResponse{}
	mi := &file_spell_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEntryResponse) ProtoMessage() {}

func (x *DeleteEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteEntryResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{24}
}

type RenameEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language the entry is for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Text is the current entry text.
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// NewText is the text to rename the entry to.
	NewText       string `protobuf:"bytes,3,opt,name=new_text,json=newText,proto3" json:"new_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameEntryRequest) Reset() {
	*x = RenameEntryRequest{}
	mi := &file_spell_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameEntryRequest) ProtoMessage() {}

func (x *RenameEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameEntryRequest.ProtoReflect.Descriptor instead.
func (*RenameEntryRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{25}
}

func (x *RenameEntryRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RenameEntryRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RenameEntryRequest) GetNewText() string {
	if x != nil {
		return x.NewText
	}
	return ""
}

type RenameEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameEntryResponse) Reset() {
	*x = RenameEntryResponse{}
	mi := &file_spell_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameEntryResponse) ProtoMessage() {}

func (x *RenameEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameEntryResponse.ProtoReflect.Descriptor instead.
func (*RenameEntryResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{26}
}

// Rule is a named pattern matcher. The pattern is matched against the text
// directly using a small DSL: "{digit}" matches a run of digits, "{word}" a run
// of letters, and "{gap}" / "{gap(N)}" up to 4 (or N) whitespace-separated
// words in between. Any other text is literal and, by default, matched
// case-insensitively. Whitespace is significant: a run of spaces means "one or
// more whitespace" and adjacency means none, so "{digit}-{digit}" matches
// "12-15" but not "12 - 15". The placeholders capture their match; reference
// them in the replacement template as {1}, {2}, … in order. For example
// "{digit}-{digit}" with replacement "{1}–{2}" turns "12-15" into "12–15".
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the sequential primary key of the rule. Zero when creating a new
	// rule; the server assigns it.
	Id int64 `protobuf:"varint,14,opt,name=id,proto3" json:"id,omitempty"`
	// Language the rule is for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Name is a human-readable label for the rule. It is not unique.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Status of the rule, used for moderation.
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Description shown to editors as context for the correction.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Level to use when offering corrections. Optional, defaults to LEVEL_ERROR.
	Level CorrectionLevel `protobuf:"varint,5,opt,name=level,proto3,enum=elephant.spell.CorrectionLevel" json:"level,omitempty"`
	// Pattern to match, in the rule DSL (see the message documentation).
	Pattern string `protobuf:"bytes,6,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// Replacement template for the suggestion, referencing captures as {1}, {2}, …
	Replacement string `protobuf:"bytes,7,opt,name=replacement,proto3" json:"replacement,omitempty"`
	// Before, when set, only matches when immediately preceded by one of these
	// words.
	Before []string `protobuf:"bytes,8,rep,name=before,proto3" json:"before,omitempty"`
	// After, when set, only matches when immediately followed by one of these
	// words.
	After []string `protobuf:"bytes,9,rep,name=after,proto3" json:"after,omitempty"`
	// NotBefore suppresses the match when preceded by one of these words.
	NotBefore []string `protobuf:"bytes,10,rep,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	// NotAfter suppresses the match when followed by one of these words.
	NotAfter []string `protobuf:"bytes,11,rep,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	// Updated is the last update time in RFC3339 format.
	Updated string `protobuf:"bytes,12,opt,name=updated,proto3" json:"updated,omitempty"`
	// UpdatedBy is the identity of the party that last updated the rule.
	UpdatedBy string `protobuf:"bytes,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	// CaseSensitive matches the pattern and guards with their exact casing when
	// set. Defaults to case-insensitive matching.
	CaseSensitive bool `protobuf:"varint,15,opt,name=case_sensitive,json=caseSensitive,proto3" json:"case_sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_spell_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{27}
}

func (x *Rule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rule) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetLevel() CorrectionLevel {
	if x != nil {
		return x.Level
	}
	return CorrectionLevel_LEVEL_UNSPECIFIED
}

func (x *Rule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Rule) GetReplacement() string {
	if x != nil {
		return x.Replacement
	}
	return ""
}

func (x *Rule) GetBefore() []string {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *Rule) GetAfter() []string {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *Rule) GetNotBefore() []string {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *Rule) GetNotAfter() []string {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *Rule) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *Rule) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Rule) GetCaseSensitive() bool {
	if x != nil {
		return x.CaseSensitive
	}
	return false
}

type ListRulesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Language to list rules for.
	Language string `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	// Page to return.
	Page int64 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// Query filters rules by a free-text substring, matched against the name,
	// description, pattern and replacement.
	Query string `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	// Status to filter rules by.
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// PageSize is the number of rules per page. Optional, defaults to 100.
	PageSize      int64 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_spell_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{28}
}

func (x *ListRulesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListRulesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRulesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListRulesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRulesRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_spell_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{29}
}

func (x *ListRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type GetRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the rule to get.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleRequest) Reset() {
	*x = GetRuleRequest{}
	mi := &file_spell_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleRequest) ProtoMessage() {}

func (x *GetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleRequest.ProtoReflect.Descriptor instead.
func (*GetRuleRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{30}
}

func (x *GetRuleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuleResponse) Reset() {
	*x = GetRuleResponse{}
	mi := &file_spell_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuleResponse) ProtoMessage() {}

func (x *GetRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuleResponse.ProtoReflect.Descriptor instead.
func (*GetRuleResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{31}
}

func (x *GetRuleResponse) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type SetRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rule to set. A zero id creates a new rule; a non-zero id updates the
	// existing rule with that id.
	Rule          *Rule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRuleRequest) Reset() {
	*x = SetRuleRequest{}
	mi := &file_spell_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRuleRequest) ProtoMessage() {}

func (x *SetRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRuleRequest.ProtoReflect.Descriptor instead.
func (*SetRuleRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{32}
}

func (x *SetRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type SetRuleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the created or updated rule.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRuleResponse) Reset() {
	*x = SetRuleResponse{}
	mi := &file_spell_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRuleResponse) ProtoMessage() {}

func (x *SetRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRuleResponse.ProtoReflect.Descriptor instead.
func (*SetRuleResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{33}
}

func (x *SetRuleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetRuleStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the rule to update.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Status to set, e.g. "accepted" or "pending".
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRuleStatusRequest) Reset() {
	*x = SetRuleStatusRequest{}
	mi := &file_spell_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRuleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRuleStatusRequest) ProtoMessage() {}

func (x *SetRuleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRuleStatusRequest.ProtoReflect.Descriptor instead.
func (*SetRuleStatusRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{34}
}

func (x *SetRuleStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SetRuleStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetRuleStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRuleStatusResponse) Reset() {
	*x = SetRuleStatusResponse{}
	mi := &file_spell_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRuleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRuleStatusResponse) ProtoMessage() {}

func (x *SetRuleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRuleStatusResponse.ProtoReflect.Descriptor instead.
func (*SetRuleStatusResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{35}
}

type DeleteRuleRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the rule to delete.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_spell_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteRuleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_spell_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spell_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_spell_service_proto_rawDescGZIP(), []int{37}
}

var File_spell_service_proto protoreflect.FileDescriptor

const file_spell_service_proto_rawDesc = "" +
	"\n" +
	"\x13spell/service.proto\x12\x0eelephant.spell\"\x1b\n" +
	"\x19SupportedLanguagesRequest\"T\n" +
	"\x1aSupportedLanguagesResponse\x126\n" +
	"\tlanguages\x18\x01 \x03(\v2\x18.elephant.spell.LanguageR\tlanguages\"\x1e\n" +
	"\bLanguage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x80\x01\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x03(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12 \n" +
	"\vsuggestions\x18\x03 \x01(\bR\vsuggestions\x12\x1f\n" +
	"\vcustom_only\x18\x04 \x01(\bR\n" +
	"customOnly\"J\n" +
	"\fTextResponse\x12:\n" +
	"\n" +
	"misspelled\x18\x01 \x03(\v2\x1a.elephant.spell.MisspelledR\n" +
	"misspelled\"G\n" +
	"\n" +
	"Misspelled\x129\n" +
	"\aentries\x18\x01 \x03(\v2\x1f.elephant.spell.MisspelledEntryR\aentries\"\xe2\x01\n" +
	"\x0fMisspelledEntry\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12<\n" +
	"\vsuggestions\x18\x02 \x03(\v2\x1a.elephant.spell.SuggestionR\vsuggestions\x125\n" +
	"\x05level\x18\x03 \x01(\x0e2\x1f.elephant.spell.CorrectionLevelR\x05level\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12.\n" +
	"\x05spans\x18\x05 \x03(\v2\x18.elephant.spell.TextSpanR\x05spans\"2\n" +
	"\bTextSpan\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"e\n" +
	"\x12SuggestionsRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x1f\n" +
	"\vcustom_only\x18\x03 \x01(\bR\n" +
	"customOnly\"S\n" +
	"\x13SuggestionsResponse\x12<\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x1a.elephant.spell.SuggestionR\vsuggestions\"B\n" +
	"\n" +
	"Suggestion\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x8f\x01\n" +
	"\x12ListEntriesRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\"L\n" +
	"\x13ListEntriesResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x1b.elephant.spell.CustomEntryR\aentries\"\x99\x04\n" +
	"\vCustomEntry\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12'\n" +
	"\x0fcommon_mistakes\x18\x05 \x03(\tR\x0ecommonMistakes\x125\n" +
	"\x05level\x18\x06 \x01(\x0e2\x1f.elephant.spell.CorrectionLevelR\x05level\x12<\n" +
	"\x05forms\x18\a \x03(\v2&.elephant.spell.CustomEntry.FormsEntryR\x05forms\x12\x18\n" +
	"\aupdated\x18\b \x01(\tR\aupdated\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\x12%\n" +
	"\x0ecase_sensitive\x18\n" +
	" \x01(\bR\rcaseSensitive\x12\x16\n" +
	"\x06before\x18\v \x03(\tR\x06before\x12\x14\n" +
	"\x05after\x18\f \x03(\tR\x05after\x12\x1d\n" +
	"\n" +
	"not_before\x18\r \x03(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x0e \x03(\tR\bnotAfter\x1a8\n" +
	"\n" +
	"FormsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x19\n" +
	"\x17ListDictionariesRequest\"`\n" +
	"\x18ListDictionariesResponse\x12D\n" +
	"\fdictionaries\x18\x01 \x03(\v2 .elephant.spell.CustomDictionaryR\fdictionaries\"\xc1\x01\n" +
	"\x10CustomDictionary\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1f\n" +
	"\ventry_count\x18\x02 \x01(\x03R\n" +
	"entryCount\x12#\n" +
	"\rpending_count\x18\x03 \x01(\x03R\fpendingCount\x12\x1d\n" +
	"\n" +
	"rule_count\x18\x04 \x01(\x03R\truleCount\x12,\n" +
	"\x12rule_pending_count\x18\x05 \x01(\x03R\x10rulePendingCount\"A\n" +
	"\x0fGetEntryRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"E\n" +
	"\x10GetEntryResponse\x121\n" +
	"\x05entry\x18\x01 \x01(\v2\x1b.elephant.spell.CustomEntryR\x05entry\"D\n" +
	"\x0fSetEntryRequest\x121\n" +
	"\x05entry\x18\x01 \x01(\v2\x1b.elephant.spell.CustomEntryR\x05entry\"\x12\n" +
	"\x10SetEntryResponse\"_\n" +
	"\x15SetEntryStatusRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x18\n" +
	"\x16SetEntryStatusResponse\"D\n" +
	"\x12DeleteEntryRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x15\n" +
	"\x13DeleteEntryResponse\"_\n" +
	"\x12RenameEntryRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x19\n" +
	"\bnew_text\x18\x03 \x01(\tR\anewText\"\x15\n" +
	"\x13RenameEntryResponse\"\xbd\x03\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x0e \x01(\x03R\x02id\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x125\n" +
	"\x05level\x18\x05 \x01(\x0e2\x1f.elephant.spell.CorrectionLevelR\x05level\x12\x18\n" +
	"\apattern\x18\x06 \x01(\tR\apattern\x12 \n" +
	"\vreplacement\x18\a \x01(\tR\vreplacement\x12\x16\n" +
	"\x06before\x18\b \x03(\tR\x06before\x12\x14\n" +
	"\x05after\x18\t \x03(\tR\x05after\x12\x1d\n" +
	"\n" +
	"not_before\x18\n" +
	" \x03(\tR\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\v \x03(\tR\bnotAfter\x12\x18\n" +
	"\aupdated\x18\f \x01(\tR\aupdated\x12\x1d\n" +
	"\n" +
	"updated_by\x18\r \x01(\tR\tupdatedBy\x12%\n" +
	"\x0ecase_sensitive\x18\x0f \x01(\bR\rcaseSensitive\"\x8d\x01\n" +
	"\x10ListRulesRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x03R\bpageSize\"?\n" +
	"\x11ListRulesResponse\x12*\n" +
	"\x05rules\x18\x01 \x03(\v2\x14.elephant.spell.RuleR\x05rules\" \n" +
	"\x0eGetRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x0fGetRuleResponse\x12(\n" +
	"\x04rule\x18\x01 \x01(\v2\x14.elephant.spell.RuleR\x04rule\":\n" +
	"\x0eSetRuleRequest\x12(\n" +
	"\x04rule\x18\x01 \x01(\v2\x14.elephant.spell.RuleR\x04rule\"!\n" +
	"\x0fSetRuleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x14SetRuleStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x17\n" +
	"\x15SetRuleStatusResponse\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteRuleResponse*O\n" +
	"\x0fCorrectionLevel\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x01\x12\x14\n" +
	"\x10LEVEL_SUGGESTION\x10\x022\xa2\x01\n" +
	"\x05Check\x12A\n" +
	"\x04Text\x12\x1b.elephant.spell.TextRequest\x1a\x1c.elephant.spell.TextResponse\x12V\n" +
	"\vSuggestions\x12\".elephant.spell.SuggestionsRequest\x1a#.elephant.spell.SuggestionsResponse2\xe9\x05\n" +
	"\fDictionaries\x12k\n" +
	"\x12SupportedLanguages\x12).elephant.spell.SupportedLanguagesRequest\x1a*.elephant.spell.SupportedLanguagesResponse\x12e\n" +
	"\x10ListDictionaries\x12'.elephant.spell.ListDictionariesRequest\x1a(.elephant.spell.ListDictionariesResponse\x12V\n" +
	"\vListEntries\x12\".elephant.spell.ListEntriesRequest\x1a#.elephant.spell.ListEntriesResponse\x12M\n" +
	"\bGetEntry\x12\x1f.elephant.spell.GetEntryRequest\x1a .elephant.spell.GetEntryResponse\x12M\n" +
	"\bSetEntry\x12\x1f.elephant.spell.SetEntryRequest\x1a .elephant.spell.SetEntryResponse\x12_\n" +
	"\x0eSetEntryStatus\x12%.elephant.spell.SetEntryStatusRequest\x1a&.elephant.spell.SetEntryStatusResponse\x12V\n" +
	"\vDeleteEntry\x12\".elephant.spell.DeleteEntryRequest\x1a#.elephant.spell.DeleteEntryResponse\x12V\n" +
	"\vRenameEntry\x12\".elephant.spell.RenameEntryRequest\x1a#.elephant.spell.RenameEntryResponse2\xa4\x03\n" +
	"\x05Rules\x12P\n" +
	"\tListRules\x12 .elephant.spell.ListRulesRequest\x1a!.elephant.spell.ListRulesResponse\x12J\n" +
	"\aGetRule\x12\x1e.elephant.spell.GetRuleRequest\x1a\x1f.elephant.spell.GetRuleResponse\x12J\n" +
	"\aSetRule\x12\x1e.elephant.spell.SetRuleRequest\x1a\x1f.elephant.spell.SetRuleResponse\x12\\\n" +
	"\rSetRuleStatus\x12$.elephant.spell.SetRuleStatusRequest\x1a%.elephant.spell.SetRuleStatusResponse\x12S\n" +
	"\n" +
	"DeleteRule\x12!.elephant.spell.DeleteRuleRequest\x1a\".elephant.spell.DeleteRuleResponseB$Z\"github.com/ttab/elephant-api/spellb\x06proto3"

var (
	file_spell_service_proto_rawDescOnce sync.Once
	file_spell_service_proto_rawDescData []byte
)

func file_spell_service_proto_rawDescGZIP() []byte {
	file_spell_service_proto_rawDescOnce.Do(func() {
		file_spell_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spell_service_proto_rawDesc), len(file_spell_service_proto_rawDesc)))
	})
	return file_spell_service_proto_rawDescData
}

var file_spell_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spell_service_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_spell_service_proto_goTypes = []any{
	(CorrectionLevel)(0),               // 0: elephant.spell.CorrectionLevel
	(*SupportedLanguagesRequest)(nil),  // 1: elephant.spell.SupportedLanguagesRequest
	(*SupportedLanguagesResponse)(nil), // 2: elephant.spell.SupportedLanguagesResponse
	(*Language)(nil),                   // 3: elephant.spell.Language
	(*TextRequest)(nil),                // 4: elephant.spell.TextRequest
	(*TextResponse)(nil),               // 5: elephant.spell.TextResponse
	(*Misspelled)(nil),                 // 6: elephant.spell.Misspelled
	(*MisspelledEntry)(nil),            // 7: elephant.spell.MisspelledEntry
	(*TextSpan)(nil),                   // 8: elephant.spell.TextSpan
	(*SuggestionsRequest)(nil),         // 9: elephant.spell.SuggestionsRequest
	(*SuggestionsResponse)(nil),        // 10: elephant.spell.SuggestionsResponse
	(*Suggestion)(nil),                 // 11: elephant.spell.Suggestion
	(*ListEntriesRequest)(nil),         // 12: elephant.spell.ListEntriesRequest
	(*ListEntriesResponse)(nil),        // 13: elephant.spell.ListEntriesResponse
	(*CustomEntry)(nil),                // 14: elephant.spell.CustomEntry
	(*ListDictionariesRequest)(nil),    // 15: elephant.spell.ListDictionariesRequest
	(*ListDictionariesResponse)(nil),   // 16: elephant.spell.ListDictionariesResponse
	(*CustomDictionary)(nil),           // 17: elephant.spell.CustomDictionary
	(*GetEntryRequest)(nil),            // 18: elephant.spell.GetEntryRequest
	(*GetEntryResponse)(nil),           // 19: elephant.spell.GetEntryResponse
	(*SetEntryRequest)(nil),            // 20: elephant.spell.SetEntryRequest
	(*SetEntryResponse)(nil),           // 21: elephant.spell.SetEntryResponse
	(*SetEntryStatusRequest)(nil),      // 22: elephant.spell.SetEntryStatusRequest
	(*SetEntryStatusResponse)(nil),     // 23: elephant.spell.SetEntryStatusResponse
	(*DeleteEntryRequest)(nil),         // 24: elephant.spell.DeleteEntryRequest
	(*DeleteEntryResponse)(nil),        // 25: elephant.spell.DeleteEntryResponse
	(*RenameEntryRequest)(nil),         // 26: elephant.spell.RenameEntryRequest
	(*RenameEntryResponse)(nil),        // 27: elephant.spell.RenameEntryResponse
	(*Rule)(nil),                       // 28: elephant.spell.Rule
	(*ListRulesRequest)(nil),           // 29: elephant.spell.ListRulesRequest
	(*ListRulesResponse)(nil),          // 30: elephant.spell.ListRulesResponse
	(*GetRuleRequest)(nil),             // 31: elephant.spell.GetRuleRequest
	(*GetRuleResponse)(nil),            // 32: elephant.spell.GetRuleResponse
	(*SetRuleRequest)(nil),             // 33: elephant.spell.SetRuleRequest
	(*SetRuleResponse)(nil),            // 34: elephant.spell.SetRuleResponse
	(*SetRuleStatusRequest)(nil),       // 35: elephant.spell.SetRuleStatusRequest
	(*SetRuleStatusResponse)(nil),      // 36: elephant.spell.SetRuleStatusResponse
	(*DeleteRuleRequest)(nil),          // 37: elephant.spell.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),         // 38: elephant.spell.DeleteRuleResponse
	nil,                                // 39: elephant.spell.CustomEntry.FormsEntry
}
var file_spell_service_proto_depIdxs = []int32{
	3,  // 0: elephant.spell.SupportedLanguagesResponse.languages:type_name -> elephant.spell.Language
	6,  // 1: elephant.spell.TextResponse.misspelled:type_name -> elephant.spell.Misspelled
	7,  // 2: elephant.spell.Misspelled.entries:type_name -> elephant.spell.MisspelledEntry
	11, // 3: elephant.spell.MisspelledEntry.suggestions:type_name -> elephant.spell.Suggestion
	0,  // 4: elephant.spell.MisspelledEntry.level:type_name -> elephant.spell.CorrectionLevel
	8,  // 5: elephant.spell.MisspelledEntry.spans:type_name -> elephant.spell.TextSpan
	11, // 6: elephant.spell.SuggestionsResponse.suggestions:type_name -> elephant.spell.Suggestion
	14, // 7: elephant.spell.ListEntriesResponse.entries:type_name -> elephant.spell.CustomEntry
	0,  // 8: elephant.spell.CustomEntry.level:type_name -> elephant.spell.CorrectionLevel
	39, // 9: elephant.spell.CustomEntry.forms:type_name -> elephant.spell.CustomEntry.FormsEntry
	17, // 10: elephant.spell.ListDictionariesResponse.dictionaries:type_name -> elephant.spell.CustomDictionary
	14, // 11: elephant.spell.GetEntryResponse.entry:type_name -> elephant.spell.CustomEntry
	14, // 12: elephant.spell.SetEntryRequest.entry:type_name -> elephant.spell.CustomEntry
	0,  // 13: elephant.spell.Rule.level:type_name -> elephant.spell.CorrectionLevel
	28, // 14: elephant.spell.ListRulesResponse.rules:type_name -> elephant.spell.Rule
	28, // 15: elephant.spell.GetRuleResponse.rule:type_name -> elephant.spell.Rule
	28, // 16: elephant.spell.SetRuleRequest.rule:type_name -> elephant.spell.Rule
	4,  // 17: elephant.spell.Check.Text:input_type -> elephant.spell.TextRequest
	9,  // 18: elephant.spell.Check.Suggestions:input_type -> elephant.spell.SuggestionsRequest
	1,  // 19: elephant.spell.Dictionaries.SupportedLanguages:input_type -> elephant.spell.SupportedLanguagesRequest
	15, // 20: elephant.spell.Dictionaries.ListDictionaries:input_type -> elephant.spell.ListDictionariesRequest
	12, // 21: elephant.spell.Dictionaries.ListEntries:input_type -> elephant.spell.ListEntriesRequest
	18, // 22: elephant.spell.Dictionaries.GetEntry:input_type -> elephant.spell.GetEntryRequest
	20, // 23: elephant.spell.Dictionaries.SetEntry:input_type -> elephant.spell.SetEntryRequest
	22, // 24: elephant.spell.Dictionaries.SetEntryStatus:input_type -> elephant.spell.SetEntryStatusRequest
	24, // 25: elephant.spell.Dictionaries.DeleteEntry:input_type -> elephant.spell.DeleteEntryRequest
	26, // 26: elephant.spell.Dictionaries.RenameEntry:input_type -> elephant.spell.RenameEntryRequest
	29, // 27: elephant.spell.Rules.ListRules:input_type -> elephant.spell.ListRulesRequest
	31, // 28: elephant.spell.Rules.GetRule:input_type -> elephant.spell.GetRuleRequest
	33, // 29: elephant.spell.Rules.SetRule:input_type -> elephant.spell.SetRuleRequest
	35, // 30: elephant.spell.Rules.SetRuleStatus:input_type -> elephant.spell.SetRuleStatusRequest
	37, // 31: elephant.spell.Rules.DeleteRule:input_type -> elephant.spell.DeleteRuleRequest
	5,  // 32: elephant.spell.Check.Text:output_type -> elephant.spell.TextResponse
	10, // 33: elephant.spell.Check.Suggestions:output_type -> elephant.spell.SuggestionsResponse
	2,  // 34: elephant.spell.Dictionaries.SupportedLanguages:output_type -> elephant.spell.SupportedLanguagesResponse
	16, // 35: elephant.spell.Dictionaries.ListDictionaries:output_type -> elephant.spell.ListDictionariesResponse
	13, // 36: elephant.spell.Dictionaries.ListEntries:output_type -> elephant.spell.ListEntriesResponse
	19, // 37: elephant.spell.Dictionaries.GetEntry:output_type -> elephant.spell.GetEntryResponse
	21, // 38: elephant.spell.Dictionaries.SetEntry:output_type -> elephant.spell.SetEntryResponse
	23, // 39: elephant.spell.Dictionaries.SetEntryStatus:output_type -> elephant.spell.SetEntryStatusResponse
	25, // 40: elephant.spell.Dictionaries.DeleteEntry:output_type -> elephant.spell.DeleteEntryResponse
	27, // 41: elephant.spell.Dictionaries.RenameEntry:output_type -> elephant.spell.RenameEntryResponse
	30, // 42: elephant.spell.Rules.ListRules:output_type -> elephant.spell.ListRulesResponse
	32, // 43: elephant.spell.Rules.GetRule:output_type -> elephant.spell.GetRuleResponse
	34, // 44: elephant.spell.Rules.SetRule:output_type -> elephant.spell.SetRuleResponse
	36, // 45: elephant.spell.Rules.SetRuleStatus:output_type -> elephant.spell.SetRuleStatusResponse
	38, // 46: elephant.spell.Rules.DeleteRule:output_type -> elephant.spell.DeleteRuleResponse
	32, // [32:47] is the sub-list for method output_type
	17, // [17:32] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_spell_service_proto_init() }
func file_spell_service_proto_init() {
	if File_spell_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spell_service_proto_rawDesc), len(file_spell_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_spell_service_proto_goTypes,
		DependencyIndexes: file_spell_service_proto_depIdxs,
		EnumInfos:         file_spell_service_proto_enumTypes,
		MessageInfos:      file_spell_service_proto_msgTypes,
	}.Build()
	File_spell_service_proto = out.File
	file_spell_service_proto_goTypes = nil
	file_spell_service_proto_depIdxs = nil
}
