// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: spell/service.proto

package spellconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	spell "github.com/ttab/elephant-api/spell"
	http "net/http"
)

// NewCheckServiceHandler builds an HTTP handler for the elephant.spell.Check service from an
// implementation of the plain spell.Check interface, and returns the path to mount it on together
// with the handler, just like NewCheckHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewCheckServiceHandler(svc spell.Check, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewCheckHandler(&checkServiceHandler{svc: svc}, opts...)
}

// checkServiceHandler implements CheckHandler on top of a spell.Check.
type checkServiceHandler struct {
	svc spell.Check
}

func (h *checkServiceHandler) Text(ctx context.Context, req *connect.Request[spell.TextRequest]) (*connect.Response[spell.TextResponse], error) {
	res, err := h.svc.Text(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *checkServiceHandler) Suggestions(ctx context.Context, req *connect.Request[spell.SuggestionsRequest]) (*connect.Response[spell.SuggestionsResponse], error) {
	res, err := h.svc.Suggestions(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewCheckServiceClient constructs a client for the elephant.spell.Check service that implements
// the plain spell.Check interface, so that it is a drop-in for the Twirp clients. The options are
// the ones NewCheckClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewCheckServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) spell.Check {
	return &checkServiceClient{
		client: NewCheckClient(httpClient, baseURL, opts...),
	}
}

// checkServiceClient implements spell.Check on top of a CheckClient.
type checkServiceClient struct {
	client CheckClient
}

func (c *checkServiceClient) Text(ctx context.Context, req *spell.TextRequest) (*spell.TextResponse, error) {
	res, err := c.client.Text(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *checkServiceClient) Suggestions(ctx context.Context, req *spell.SuggestionsRequest) (*spell.SuggestionsResponse, error) {
	res, err := c.client.Suggestions(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewDictionariesServiceHandler builds an HTTP handler for the elephant.spell.Dictionaries service
// from an implementation of the plain spell.Dictionaries interface, and returns the path to mount
// it on together with the handler, just like NewDictionariesHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewDictionariesServiceHandler(svc spell.Dictionaries, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewDictionariesHandler(&dictionariesServiceHandler{svc: svc}, opts...)
}

// dictionariesServiceHandler implements DictionariesHandler on top of a spell.Dictionaries.
type dictionariesServiceHandler struct {
	svc spell.Dictionaries
}

func (h *dictionariesServiceHandler) SupportedLanguages(ctx context.Context, req *connect.Request[spell.SupportedLanguagesRequest]) (*connect.Response[spell.SupportedLanguagesResponse], error) {
	res, err := h.svc.SupportedLanguages(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *dictionariesServiceHandler) ListDictionaries(ctx context.Context, req *connect.Request[spell.ListDictionariesRequest]) (*connect.Response[spell.ListDictionariesResponse], error) {
	res, err := h.svc.ListDictionaries(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *dictionariesServiceHandler) ListEntries(ctx context.Context, req *connect.Request[spell.ListEntriesRequest]) (*connect.Response[spell.ListEntriesResponse], error) {
	res, err := h.svc.ListEntries(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *dictionariesServiceHandler) GetEntry(ctx context.Context, req *connect.Request[spell.GetEntryRequest]) (*connect.Response[spell.GetEntryResponse], error) {
	res, err := h.svc.GetEntry(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *dictionariesServiceHandler) SetEntry(ctx context.Context, req *connect.Request[spell.SetEntryRequest]) (*connect.Response[spell.SetEntryResponse], error) {
	res, err := h.svc.SetEntry(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *dictionariesServiceHandler) SetEntryStatus(ctx context.Context, req *connect.Request[spell.SetEntryStatusRequest]) (*connect.Response[spell.SetEntryStatusResponse], error) {
	res, err := h.svc.SetEntryStatus(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *dictionariesServiceHandler) DeleteEntry(ctx context.Context, req *connect.Request[spell.DeleteEntryRequest]) (*connect.Response[spell.DeleteEntryResponse], error) {
	res, err := h.svc.DeleteEntry(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *dictionariesServiceHandler) RenameEntry(ctx context.Context, req *connect.Request[spell.RenameEntryRequest]) (*connect.Response[spell.RenameEntryResponse], error) {
	res, err := h.svc.RenameEntry(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewDictionariesServiceClient constructs a client for the elephant.spell.Dictionaries service that
// implements the plain spell.Dictionaries interface, so that it is a drop-in for the Twirp clients.
// The options are the ones NewDictionariesClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewDictionariesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) spell.Dictionaries {
	return &dictionariesServiceClient{
		client: NewDictionariesClient(httpClient, baseURL, opts...),
	}
}

// dictionariesServiceClient implements spell.Dictionaries on top of a DictionariesClient.
type dictionariesServiceClient struct {
	client DictionariesClient
}

func (c *dictionariesServiceClient) SupportedLanguages(ctx context.Context, req *spell.SupportedLanguagesRequest) (*spell.SupportedLanguagesResponse, error) {
	res, err := c.client.SupportedLanguages(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *dictionariesServiceClient) ListDictionaries(ctx context.Context, req *spell.ListDictionariesRequest) (*spell.ListDictionariesResponse, error) {
	res, err := c.client.ListDictionaries(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *dictionariesServiceClient) ListEntries(ctx context.Context, req *spell.ListEntriesRequest) (*spell.ListEntriesResponse, error) {
	res, err := c.client.ListEntries(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *dictionariesServiceClient) GetEntry(ctx context.Context, req *spell.GetEntryRequest) (*spell.GetEntryResponse, error) {
	res, err := c.client.GetEntry(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *dictionariesServiceClient) SetEntry(ctx context.Context, req *spell.SetEntryRequest) (*spell.SetEntryResponse, error) {
	res, err := c.client.SetEntry(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *dictionariesServiceClient) SetEntryStatus(ctx context.Context, req *spell.SetEntryStatusRequest) (*spell.SetEntryStatusResponse, error) {
	res, err := c.client.SetEntryStatus(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *dictionariesServiceClient) DeleteEntry(ctx context.Context, req *spell.DeleteEntryRequest) (*spell.DeleteEntryResponse, error) {
	res, err := c.client.DeleteEntry(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *dictionariesServiceClient) RenameEntry(ctx context.Context, req *spell.RenameEntryRequest) (*spell.RenameEntryResponse, error) {
	res, err := c.client.RenameEntry(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewRulesServiceHandler builds an HTTP handler for the elephant.spell.Rules service from an
// implementation of the plain spell.Rules interface, and returns the path to mount it on together
// with the handler, just like NewRulesHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewRulesServiceHandler(svc spell.Rules, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewRulesHandler(&rulesServiceHandler{svc: svc}, opts...)
}

// rulesServiceHandler implements RulesHandler on top of a spell.Rules.
type rulesServiceHandler struct {
	svc spell.Rules
}

func (h *rulesServiceHandler) ListRules(ctx context.Context, req *connect.Request[spell.ListRulesRequest]) (*connect.Response[spell.ListRulesResponse], error) {
	res, err := h.svc.ListRules(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *rulesServiceHandler) GetRule(ctx context.Context, req *connect.Request[spell.GetRuleRequest]) (*connect.Response[spell.GetRuleResponse], error) {
	res, err := h.svc.GetRule(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *rulesServiceHandler) SetRule(ctx context.Context, req *connect.Request[spell.SetRuleRequest]) (*connect.Response[spell.SetRuleResponse], error) {
	res, err := h.svc.SetRule(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *rulesServiceHandler) SetRuleStatus(ctx context.Context, req *connect.Request[spell.SetRuleStatusRequest]) (*connect.Response[spell.SetRuleStatusResponse], error) {
	res, err := h.svc.SetRuleStatus(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *rulesServiceHandler) DeleteRule(ctx context.Context, req *connect.Request[spell.DeleteRuleRequest]) (*connect.Response[spell.DeleteRuleResponse], error) {
	res, err := h.svc.DeleteRule(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewRulesServiceClient constructs a client for the elephant.spell.Rules service that implements
// the plain spell.Rules interface, so that it is a drop-in for the Twirp clients. The options are
// the ones NewRulesClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewRulesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) spell.Rules {
	return &rulesServiceClient{
		client: NewRulesClient(httpClient, baseURL, opts...),
	}
}

// rulesServiceClient implements spell.Rules on top of a RulesClient.
type rulesServiceClient struct {
	client RulesClient
}

func (c *rulesServiceClient) ListRules(ctx context.Context, req *spell.ListRulesRequest) (*spell.ListRulesResponse, error) {
	res, err := c.client.ListRules(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *rulesServiceClient) GetRule(ctx context.Context, req *spell.GetRuleRequest) (*spell.GetRuleResponse, error) {
	res, err := c.client.GetRule(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *rulesServiceClient) SetRule(ctx context.Context, req *spell.SetRuleRequest) (*spell.SetRuleResponse, error) {
	res, err := c.client.SetRule(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *rulesServiceClient) SetRuleStatus(ctx context.Context, req *spell.SetRuleStatusRequest) (*spell.SetRuleStatusResponse, error) {
	res, err := c.client.SetRuleStatus(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *rulesServiceClient) DeleteRule(ctx context.Context, req *spell.DeleteRuleRequest) (*spell.DeleteRuleResponse, error) {
	res, err := c.client.DeleteRule(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
