// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: spell/service.proto

package spellconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	spell "github.com/ttab/elephant-api/spell"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CheckName is the fully-qualified name of the Check service.
	CheckName = "elephant.spell.Check"
	// DictionariesName is the fully-qualified name of the Dictionaries service.
	DictionariesName = "elephant.spell.Dictionaries"
	// RulesName is the fully-qualified name of the Rules service.
	RulesName = "elephant.spell.Rules"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CheckTextProcedure is the fully-qualified name of the Check's Text RPC.
	CheckTextProcedure = "/elephant.spell.Check/Text"
	// CheckSuggestionsProcedure is the fully-qualified name of the Check's Suggestions RPC.
	CheckSuggestionsProcedure = "/elephant.spell.Check/Suggestions"
	// DictionariesSupportedLanguagesProcedure is the fully-qualified name of the Dictionaries's
	// SupportedLanguages RPC.
	DictionariesSupportedLanguagesProcedure = "/elephant.spell.Dictionaries/SupportedLanguages"
	// DictionariesListDictionariesProcedure is the fully-qualified name of the Dictionaries's
	// ListDictionaries RPC.
	DictionariesListDictionariesProcedure = "/elephant.spell.Dictionaries/ListDictionaries"
	// DictionariesListEntriesProcedure is the fully-qualified name of the Dictionaries's ListEntries
	// RPC.
	DictionariesListEntriesProcedure = "/elephant.spell.Dictionaries/ListEntries"
	// DictionariesGetEntryProcedure is the fully-qualified name of the Dictionaries's GetEntry RPC.
	DictionariesGetEntryProcedure = "/elephant.spell.Dictionaries/GetEntry"
	// DictionariesSetEntryProcedure is the fully-qualified name of the Dictionaries's SetEntry RPC.
	DictionariesSetEntryProcedure = "/elephant.spell.Dictionaries/SetEntry"
	// DictionariesSetEntryStatusProcedure is the fully-qualified name of the Dictionaries's
	// SetEntryStatus RPC.
	DictionariesSetEntryStatusProcedure = "/elephant.spell.Dictionaries/SetEntryStatus"
	// DictionariesDeleteEntryProcedure is the fully-qualified name of the Dictionaries's DeleteEntry
	// RPC.
	DictionariesDeleteEntryProcedure = "/elephant.spell.Dictionaries/DeleteEntry"
	// DictionariesRenameEntryProcedure is the fully-qualified name of the Dictionaries's RenameEntry
	// RPC.
	DictionariesRenameEntryProcedure = "/elephant.spell.Dictionaries/RenameEntry"
	// RulesListRulesProcedure is the fully-qualified name of the Rules's ListRules RPC.
	RulesListRulesProcedure = "/elephant.spell.Rules/ListRules"
	// RulesGetRuleProcedure is the fully-qualified name of the Rules's GetRule RPC.
	RulesGetRuleProcedure = "/elephant.spell.Rules/GetRule"
	// RulesSetRuleProcedure is the fully-qualified name of the Rules's SetRule RPC.
	RulesSetRuleProcedure = "/elephant.spell.Rules/SetRule"
	// RulesSetRuleStatusProcedure is the fully-qualified name of the Rules's SetRuleStatus RPC.
	RulesSetRuleStatusProcedure = "/elephant.spell.Rules/SetRuleStatus"
	// RulesDeleteRuleProcedure is the fully-qualified name of the Rules's DeleteRule RPC.
	RulesDeleteRuleProcedure = "/elephant.spell.Rules/DeleteRule"
)

// CheckClient is a client for the elephant.spell.Check service.
type CheckClient interface {
	// Text spellchecks a text and returns the misspelled words or phrases.
	Text(context.Context, *connect.Request[spell.TextRequest]) (*connect.Response[spell.TextResponse], error)
	// Suggestions returns suggestions for a word or phrase.
	Suggestions(context.Context, *connect.Request[spell.SuggestionsRequest]) (*connect.Response[spell.SuggestionsResponse], error)
}

// NewCheckClient constructs a client for the elephant.spell.Check service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCheckClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CheckClient {
	baseURL = strings.TrimRight(baseURL, "/")
	checkMethods := spell.File_spell_service_proto.Services().ByName("Check").Methods()
	return &checkClient{
		text: connect.NewClient[spell.TextRequest, spell.TextResponse](
			httpClient,
			baseURL+CheckTextProcedure,
			connect.WithSchema(checkMethods.ByName("Text")),
			connect.WithClientOptions(opts...),
		),
		suggestions: connect.NewClient[spell.SuggestionsRequest, spell.SuggestionsResponse](
			httpClient,
			baseURL+CheckSuggestionsProcedure,
			connect.WithSchema(checkMethods.ByName("Suggestions")),
			connect.WithClientOptions(opts...),
		),
	}
}

// checkClient implements CheckClient.
type checkClient struct {
	text        *connect.Client[spell.TextRequest, spell.TextResponse]
	suggestions *connect.Client[spell.SuggestionsRequest, spell.SuggestionsResponse]
}

// Text calls elephant.spell.Check.Text.
func (c *checkClient) Text(ctx context.Context, req *connect.Request[spell.TextRequest]) (*connect.Response[spell.TextResponse], error) {
	return c.text.CallUnary(ctx, req)
}

// Suggestions calls elephant.spell.Check.Suggestions.
func (c *checkClient) Suggestions(ctx context.Context, req *connect.Request[spell.SuggestionsRequest]) (*connect.Response[spell.SuggestionsResponse], error) {
	return c.suggestions.CallUnary(ctx, req)
}

// CheckHandler is an implementation of the elephant.spell.Check service.
type CheckHandler interface {
	// Text spellchecks a text and returns the misspelled words or phrases.
	Text(context.Context, *connect.Request[spell.TextRequest]) (*connect.Response[spell.TextResponse], error)
	// Suggestions returns suggestions for a word or phrase.
	Suggestions(context.Context, *connect.Request[spell.SuggestionsRequest]) (*connect.Response[spell.SuggestionsResponse], error)
}

// NewCheckHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCheckHandler(svc CheckHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	checkMethods := spell.File_spell_service_proto.Services().ByName("Check").Methods()
	checkTextHandler := connect.NewUnaryHandler(
		CheckTextProcedure,
		svc.Text,
		connect.WithSchema(checkMethods.ByName("Text")),
		connect.WithHandlerOptions(opts...),
	)
	checkSuggestionsHandler := connect.NewUnaryHandler(
		CheckSuggestionsProcedure,
		svc.Suggestions,
		connect.WithSchema(checkMethods.ByName("Suggestions")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephant.spell.Check/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CheckTextProcedure:
			checkTextHandler.ServeHTTP(w, r)
		case CheckSuggestionsProcedure:
			checkSuggestionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCheckHandler returns CodeUnimplemented from all methods.
type UnimplementedCheckHandler struct{}

func (UnimplementedCheckHandler) Text(context.Context, *connect.Request[spell.TextRequest]) (*connect.Response[spell.TextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Check.Text is not implemented"))
}

func (UnimplementedCheckHandler) Suggestions(context.Context, *connect.Request[spell.SuggestionsRequest]) (*connect.Response[spell.SuggestionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Check.Suggestions is not implemented"))
}

// DictionariesClient is a client for the elephant.spell.Dictionaries service.
type DictionariesClient interface {
	// SupportedLanguages returns a list of supported languages.
	SupportedLanguages(context.Context, *connect.Request[spell.SupportedLanguagesRequest]) (*connect.Response[spell.SupportedLanguagesResponse], error)
	// ListDictionaries lists the currently available custom dictionaries.
	ListDictionaries(context.Context, *connect.Request[spell.ListDictionariesRequest]) (*connect.Response[spell.ListDictionariesResponse], error)
	// ListEntries lists entries in the custom dictionaries.
	ListEntries(context.Context, *connect.Request[spell.ListEntriesRequest]) (*connect.Response[spell.ListEntriesResponse], error)
	// GetEntry returns the details of a custom word or phrase.
	GetEntry(context.Context, *connect.Request[spell.GetEntryRequest]) (*connect.Response[spell.GetEntryResponse], error)
	// SetEntry is used to add or update custom dictionary entries.
	SetEntry(context.Context, *connect.Request[spell.SetEntryRequest]) (*connect.Response[spell.SetEntryResponse], error)
	// SetEntryStatus updates only the moderation status of an entry. It is a
	// lightweight alternative to SetEntry for accept/reject workflows that don't
	// need to round-trip the whole entry.
	SetEntryStatus(context.Context, *connect.Request[spell.SetEntryStatusRequest]) (*connect.Response[spell.SetEntryStatusResponse], error)
	// DeleteEntry is used to remove an entry.
	DeleteEntry(context.Context, *connect.Request[spell.DeleteEntryRequest]) (*connect.Response[spell.DeleteEntryResponse], error)
	// RenameEntry changes the text of a custom dictionary entry, keeping the rest
	// of its data. The text is the entry's identity, so renaming is a dedicated
	// operation rather than a SetEntry.
	RenameEntry(context.Context, *connect.Request[spell.RenameEntryRequest]) (*connect.Response[spell.RenameEntryResponse], error)
}

// NewDictionariesClient constructs a client for the elephant.spell.Dictionaries service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDictionariesClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DictionariesClient {
	baseURL = strings.TrimRight(baseURL, "/")
	dictionariesMethods := spell.File_spell_service_proto.Services().ByName("Dictionaries").Methods()
	return &dictionariesClient{
		supportedLanguages: connect.NewClient[spell.SupportedLanguagesRequest, spell.SupportedLanguagesResponse](
			httpClient,
			baseURL+DictionariesSupportedLanguagesProcedure,
			connect.WithSchema(dictionariesMethods.ByName("SupportedLanguages")),
			connect.WithClientOptions(opts...),
		),
		listDictionaries: connect.NewClient[spell.ListDictionariesRequest, spell.ListDictionariesResponse](
			httpClient,
			baseURL+DictionariesListDictionariesProcedure,
			connect.WithSchema(dictionariesMethods.ByName("ListDictionaries")),
			connect.WithClientOptions(opts...),
		),
		listEntries: connect.NewClient[spell.ListEntriesRequest, spell.ListEntriesResponse](
			httpClient,
			baseURL+DictionariesListEntriesProcedure,
			connect.WithSchema(dictionariesMethods.ByName("ListEntries")),
			connect.WithClientOptions(opts...),
		),
		getEntry: connect.NewClient[spell.GetEntryRequest, spell.GetEntryResponse](
			httpClient,
			baseURL+DictionariesGetEntryProcedure,
			connect.WithSchema(dictionariesMethods.ByName("GetEntry")),
			connect.WithClientOptions(opts...),
		),
		setEntry: connect.NewClient[spell.SetEntryRequest, spell.SetEntryResponse](
			httpClient,
			baseURL+DictionariesSetEntryProcedure,
			connect.WithSchema(dictionariesMethods.ByName("SetEntry")),
			connect.WithClientOptions(opts...),
		),
		setEntryStatus: connect.NewClient[spell.SetEntryStatusRequest, spell.SetEntryStatusResponse](
			httpClient,
			baseURL+DictionariesSetEntryStatusProcedure,
			connect.WithSchema(dictionariesMethods.ByName("SetEntryStatus")),
			connect.WithClientOptions(opts...),
		),
		deleteEntry: connect.NewClient[spell.DeleteEntryRequest, spell.DeleteEntryResponse](
			httpClient,
			baseURL+DictionariesDeleteEntryProcedure,
			connect.WithSchema(dictionariesMethods.ByName("DeleteEntry")),
			connect.WithClientOptions(opts...),
		),
		renameEntry: connect.NewClient[spell.RenameEntryRequest, spell.RenameEntryResponse](
			httpClient,
			baseURL+DictionariesRenameEntryProcedure,
			connect.WithSchema(dictionariesMethods.ByName("RenameEntry")),
			connect.WithClientOptions(opts...),
		),
	}
}

// dictionariesClient implements DictionariesClient.
type dictionariesClient struct {
	supportedLanguages *connect.Client[spell.SupportedLanguagesRequest, spell.SupportedLanguagesResponse]
	listDictionaries   *connect.Client[spell.ListDictionariesRequest, spell.ListDictionariesResponse]
	listEntries        *connect.Client[spell.ListEntriesRequest, spell.ListEntriesResponse]
	getEntry           *connect.Client[spell.GetEntryRequest, spell.GetEntryResponse]
	setEntry           *connect.Client[spell.SetEntryRequest, spell.SetEntryResponse]
	setEntryStatus     *connect.Client[spell.SetEntryStatusRequest, spell.SetEntryStatusResponse]
	deleteEntry        *connect.Client[spell.DeleteEntryRequest, spell.DeleteEntryResponse]
	renameEntry        *connect.Client[spell.RenameEntryRequest, spell.RenameEntryResponse]
}

// SupportedLanguages calls elephant.spell.Dictionaries.SupportedLanguages.
func (c *dictionariesClient) SupportedLanguages(ctx context.Context, req *connect.Request[spell.SupportedLanguagesRequest]) (*connect.Response[spell.SupportedLanguagesResponse], error) {
	return c.supportedLanguages.CallUnary(ctx, req)
}

// ListDictionaries calls elephant.spell.Dictionaries.ListDictionaries.
func (c *dictionariesClient) ListDictionaries(ctx context.Context, req *connect.Request[spell.ListDictionariesRequest]) (*connect.Response[spell.ListDictionariesResponse], error) {
	return c.listDictionaries.CallUnary(ctx, req)
}

// ListEntries calls elephant.spell.Dictionaries.ListEntries.
func (c *dictionariesClient) ListEntries(ctx context.Context, req *connect.Request[spell.ListEntriesRequest]) (*connect.Response[spell.ListEntriesResponse], error) {
	return c.listEntries.CallUnary(ctx, req)
}

// GetEntry calls elephant.spell.Dictionaries.GetEntry.
func (c *dictionariesClient) GetEntry(ctx context.Context, req *connect.Request[spell.GetEntryRequest]) (*connect.Response[spell.GetEntryResponse], error) {
	return c.getEntry.CallUnary(ctx, req)
}

// SetEntry calls elephant.spell.Dictionaries.SetEntry.
func (c *dictionariesClient) SetEntry(ctx context.Context, req *connect.Request[spell.SetEntryRequest]) (*connect.Response[spell.SetEntryResponse], error) {
	return c.setEntry.CallUnary(ctx, req)
}

// SetEntryStatus calls elephant.spell.Dictionaries.SetEntryStatus.
func (c *dictionariesClient) SetEntryStatus(ctx context.Context, req *connect.Request[spell.SetEntryStatusRequest]) (*connect.Response[spell.SetEntryStatusResponse], error) {
	return c.setEntryStatus.CallUnary(ctx, req)
}

// DeleteEntry calls elephant.spell.Dictionaries.DeleteEntry.
func (c *dictionariesClient) DeleteEntry(ctx context.Context, req *connect.Request[spell.DeleteEntryRequest]) (*connect.Response[spell.DeleteEntryResponse], error) {
	return c.deleteEntry.CallUnary(ctx, req)
}

// RenameEntry calls elephant.spell.Dictionaries.RenameEntry.
func (c *dictionariesClient) RenameEntry(ctx context.Context, req *connect.Request[spell.RenameEntryRequest]) (*connect.Response[spell.RenameEntryResponse], error) {
	return c.renameEntry.CallUnary(ctx, req)
}

// DictionariesHandler is an implementation of the elephant.spell.Dictionaries service.
type DictionariesHandler interface {
	// SupportedLanguages returns a list of supported languages.
	SupportedLanguages(context.Context, *connect.Request[spell.SupportedLanguagesRequest]) (*connect.Response[spell.SupportedLanguagesResponse], error)
	// ListDictionaries lists the currently available custom dictionaries.
	ListDictionaries(context.Context, *connect.Request[spell.ListDictionariesRequest]) (*connect.Response[spell.ListDictionariesResponse], error)
	// ListEntries lists entries in the custom dictionaries.
	ListEntries(context.Context, *connect.Request[spell.ListEntriesRequest]) (*connect.Response[spell.ListEntriesResponse], error)
	// GetEntry returns the details of a custom word or phrase.
	GetEntry(context.Context, *connect.Request[spell.GetEntryRequest]) (*connect.Response[spell.GetEntryResponse], error)
	// SetEntry is used to add or update custom dictionary entries.
	SetEntry(context.Context, *connect.Request[spell.SetEntryRequest]) (*connect.Response[spell.SetEntryResponse], error)
	// SetEntryStatus updates only the moderation status of an entry. It is a
	// lightweight alternative to SetEntry for accept/reject workflows that don't
	// need to round-trip the whole entry.
	SetEntryStatus(context.Context, *connect.Request[spell.SetEntryStatusRequest]) (*connect.Response[spell.SetEntryStatusResponse], error)
	// DeleteEntry is used to remove an entry.
	DeleteEntry(context.Context, *connect.Request[spell.DeleteEntryRequest]) (*connect.Response[spell.DeleteEntryResponse], error)
	// RenameEntry changes the text of a custom dictionary entry, keeping the rest
	// of its data. The text is the entry's identity, so renaming is a dedicated
	// operation rather than a SetEntry.
	RenameEntry(context.Context, *connect.Request[spell.RenameEntryRequest]) (*connect.Response[spell.RenameEntryResponse], error)
}

// NewDictionariesHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDictionariesHandler(svc DictionariesHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	dictionariesMethods := spell.File_spell_service_proto.Services().ByName("Dictionaries").Methods()
	dictionariesSupportedLanguagesHandler := connect.NewUnaryHandler(
		DictionariesSupportedLanguagesProcedure,
		svc.SupportedLanguages,
		connect.WithSchema(dictionariesMethods.ByName("SupportedLanguages")),
		connect.WithHandlerOptions(opts...),
	)
	dictionariesListDictionariesHandler := connect.NewUnaryHandler(
		DictionariesListDictionariesProcedure,
		svc.ListDictionaries,
		connect.WithSchema(dictionariesMethods.ByName("ListDictionaries")),
		connect.WithHandlerOptions(opts...),
	)
	dictionariesListEntriesHandler := connect.NewUnaryHandler(
		DictionariesListEntriesProcedure,
		svc.ListEntries,
		connect.WithSchema(dictionariesMethods.ByName("ListEntries")),
		connect.WithHandlerOptions(opts...),
	)
	dictionariesGetEntryHandler := connect.NewUnaryHandler(
		DictionariesGetEntryProcedure,
		svc.GetEntry,
		connect.WithSchema(dictionariesMethods.ByName("GetEntry")),
		connect.WithHandlerOptions(opts...),
	)
	dictionariesSetEntryHandler := connect.NewUnaryHandler(
		DictionariesSetEntryProcedure,
		svc.SetEntry,
		connect.WithSchema(dictionariesMethods.ByName("SetEntry")),
		connect.WithHandlerOptions(opts...),
	)
	dictionariesSetEntryStatusHandler := connect.NewUnaryHandler(
		DictionariesSetEntryStatusProcedure,
		svc.SetEntryStatus,
		connect.WithSchema(dictionariesMethods.ByName("SetEntryStatus")),
		connect.WithHandlerOptions(opts...),
	)
	dictionariesDeleteEntryHandler := connect.NewUnaryHandler(
		DictionariesDeleteEntryProcedure,
		svc.DeleteEntry,
		connect.WithSchema(dictionariesMethods.ByName("DeleteEntry")),
		connect.WithHandlerOptions(opts...),
	)
	dictionariesRenameEntryHandler := connect.NewUnaryHandler(
		DictionariesRenameEntryProcedure,
		svc.RenameEntry,
		connect.WithSchema(dictionariesMethods.ByName("RenameEntry")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephant.spell.Dictionaries/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DictionariesSupportedLanguagesProcedure:
			dictionariesSupportedLanguagesHandler.ServeHTTP(w, r)
		case DictionariesListDictionariesProcedure:
			dictionariesListDictionariesHandler.ServeHTTP(w, r)
		case DictionariesListEntriesProcedure:
			dictionariesListEntriesHandler.ServeHTTP(w, r)
		case DictionariesGetEntryProcedure:
			dictionariesGetEntryHandler.ServeHTTP(w, r)
		case DictionariesSetEntryProcedure:
			dictionariesSetEntryHandler.ServeHTTP(w, r)
		case DictionariesSetEntryStatusProcedure:
			dictionariesSetEntryStatusHandler.ServeHTTP(w, r)
		case DictionariesDeleteEntryProcedure:
			dictionariesDeleteEntryHandler.ServeHTTP(w, r)
		case DictionariesRenameEntryProcedure:
			dictionariesRenameEntryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDictionariesHandler returns CodeUnimplemented from all methods.
type UnimplementedDictionariesHandler struct{}

func (UnimplementedDictionariesHandler) SupportedLanguages(context.Context, *connect.Request[spell.SupportedLanguagesRequest]) (*connect.Response[spell.SupportedLanguagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Dictionaries.SupportedLanguages is not implemented"))
}

func (UnimplementedDictionariesHandler) ListDictionaries(context.Context, *connect.Request[spell.ListDictionariesRequest]) (*connect.Response[spell.ListDictionariesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Dictionaries.ListDictionaries is not implemented"))
}

func (UnimplementedDictionariesHandler) ListEntries(context.Context, *connect.Request[spell.ListEntriesRequest]) (*connect.Response[spell.ListEntriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Dictionaries.ListEntries is not implemented"))
}

func (UnimplementedDictionariesHandler) GetEntry(context.Context, *connect.Request[spell.GetEntryRequest]) (*connect.Response[spell.GetEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Dictionaries.GetEntry is not implemented"))
}

func (UnimplementedDictionariesHandler) SetEntry(context.Context, *connect.Request[spell.SetEntryRequest]) (*connect.Response[spell.SetEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Dictionaries.SetEntry is not implemented"))
}

func (UnimplementedDictionariesHandler) SetEntryStatus(context.Context, *connect.Request[spell.SetEntryStatusRequest]) (*connect.Response[spell.SetEntryStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Dictionaries.SetEntryStatus is not implemented"))
}

func (UnimplementedDictionariesHandler) DeleteEntry(context.Context, *connect.Request[spell.DeleteEntryRequest]) (*connect.Response[spell.DeleteEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Dictionaries.DeleteEntry is not implemented"))
}

func (UnimplementedDictionariesHandler) RenameEntry(context.Context, *connect.Request[spell.RenameEntryRequest]) (*connect.Response[spell.RenameEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Dictionaries.RenameEntry is not implemented"))
}

// RulesClient is a client for the elephant.spell.Rules service.
type RulesClient interface {
	// ListRules lists pattern rules.
	ListRules(context.Context, *connect.Request[spell.ListRulesRequest]) (*connect.Response[spell.ListRulesResponse], error)
	// GetRule returns the details of a single rule.
	GetRule(context.Context, *connect.Request[spell.GetRuleRequest]) (*connect.Response[spell.GetRuleResponse], error)
	// SetRule adds or updates a rule.
	SetRule(context.Context, *connect.Request[spell.SetRuleRequest]) (*connect.Response[spell.SetRuleResponse], error)
	// SetRuleStatus updates only the moderation status of a rule.
	SetRuleStatus(context.Context, *connect.Request[spell.SetRuleStatusRequest]) (*connect.Response[spell.SetRuleStatusResponse], error)
	// DeleteRule removes a rule.
	DeleteRule(context.Context, *connect.Request[spell.DeleteRuleRequest]) (*connect.Response[spell.DeleteRuleResponse], error)
}

// NewRulesClient constructs a client for the elephant.spell.Rules service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRulesClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RulesClient {
	baseURL = strings.TrimRight(baseURL, "/")
	rulesMethods := spell.File_spell_service_proto.Services().ByName("Rules").Methods()
	return &rulesClient{
		listRules: connect.NewClient[spell.ListRulesRequest, spell.ListRulesResponse](
			httpClient,
			baseURL+RulesListRulesProcedure,
			connect.WithSchema(rulesMethods.ByName("ListRules")),
			connect.WithClientOptions(opts...),
		),
		getRule: connect.NewClient[spell.GetRuleRequest, spell.GetRuleResponse](
			httpClient,
			baseURL+RulesGetRuleProcedure,
			connect.WithSchema(rulesMethods.ByName("GetRule")),
			connect.WithClientOptions(opts...),
		),
		setRule: connect.NewClient[spell.SetRuleRequest, spell.SetRuleResponse](
			httpClient,
			baseURL+RulesSetRuleProcedure,
			connect.WithSchema(rulesMethods.ByName("SetRule")),
			connect.WithClientOptions(opts...),
		),
		setRuleStatus: connect.NewClient[spell.SetRuleStatusRequest, spell.SetRuleStatusResponse](
			httpClient,
			baseURL+RulesSetRuleStatusProcedure,
			connect.WithSchema(rulesMethods.ByName("SetRuleStatus")),
			connect.WithClientOptions(opts...),
		),
		deleteRule: connect.NewClient[spell.DeleteRuleRequest, spell.DeleteRuleResponse](
			httpClient,
			baseURL+RulesDeleteRuleProcedure,
			connect.WithSchema(rulesMethods.ByName("DeleteRule")),
			connect.WithClientOptions(opts...),
		),
	}
}

// rulesClient implements RulesClient.
type rulesClient struct {
	listRules     *connect.Client[spell.ListRulesRequest, spell.ListRulesResponse]
	getRule       *connect.Client[spell.GetRuleRequest, spell.GetRuleResponse]
	setRule       *connect.Client[spell.SetRuleRequest, spell.SetRuleResponse]
	setRuleStatus *connect.Client[spell.SetRuleStatusRequest, spell.SetRuleStatusResponse]
	deleteRule    *connect.Client[spell.DeleteRuleRequest, spell.DeleteRuleResponse]
}

// ListRules calls elephant.spell.Rules.ListRules.
func (c *rulesClient) ListRules(ctx context.Context, req *connect.Request[spell.ListRulesRequest]) (*connect.Response[spell.ListRulesResponse], error) {
	return c.listRules.CallUnary(ctx, req)
}

// GetRule calls elephant.spell.Rules.GetRule.
func (c *rulesClient) GetRule(ctx context.Context, req *connect.Request[spell.GetRuleRequest]) (*connect.Response[spell.GetRuleResponse], error) {
	return c.getRule.CallUnary(ctx, req)
}

// SetRule calls elephant.spell.Rules.SetRule.
func (c *rulesClient) SetRule(ctx context.Context, req *connect.Request[spell.SetRuleRequest]) (*connect.Response[spell.SetRuleResponse], error) {
	return c.setRule.CallUnary(ctx, req)
}

// SetRuleStatus calls elephant.spell.Rules.SetRuleStatus.
func (c *rulesClient) SetRuleStatus(ctx context.Context, req *connect.Request[spell.SetRuleStatusRequest]) (*connect.Response[spell.SetRuleStatusResponse], error) {
	return c.setRuleStatus.CallUnary(ctx, req)
}

// DeleteRule calls elephant.spell.Rules.DeleteRule.
func (c *rulesClient) DeleteRule(ctx context.Context, req *connect.Request[spell.DeleteRuleRequest]) (*connect.Response[spell.DeleteRuleResponse], error) {
	return c.deleteRule.CallUnary(ctx, req)
}

// RulesHandler is an implementation of the elephant.spell.Rules service.
type RulesHandler interface {
	// ListRules lists pattern rules.
	ListRules(context.Context, *connect.Request[spell.ListRulesRequest]) (*connect.Response[spell.ListRulesResponse], error)
	// GetRule returns the details of a single rule.
	GetRule(context.Context, *connect.Request[spell.GetRuleRequest]) (*connect.Response[spell.GetRuleResponse], error)
	// SetRule adds or updates a rule.
	SetRule(context.Context, *connect.Request[spell.SetRuleRequest]) (*connect.Response[spell.SetRuleResponse], error)
	// SetRuleStatus updates only the moderation status of a rule.
	SetRuleStatus(context.Context, *connect.Request[spell.SetRuleStatusRequest]) (*connect.Response[spell.SetRuleStatusResponse], error)
	// DeleteRule removes a rule.
	DeleteRule(context.Context, *connect.Request[spell.DeleteRuleRequest]) (*connect.Response[spell.DeleteRuleResponse], error)
}

// NewRulesHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRulesHandler(svc RulesHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	rulesMethods := spell.File_spell_service_proto.Services().ByName("Rules").Methods()
	rulesListRulesHandler := connect.NewUnaryHandler(
		RulesListRulesProcedure,
		svc.ListRules,
		connect.WithSchema(rulesMethods.ByName("ListRules")),
		connect.WithHandlerOptions(opts...),
	)
	rulesGetRuleHandler := connect.NewUnaryHandler(
		RulesGetRuleProcedure,
		svc.GetRule,
		connect.WithSchema(rulesMethods.ByName("GetRule")),
		connect.WithHandlerOptions(opts...),
	)
	rulesSetRuleHandler := connect.NewUnaryHandler(
		RulesSetRuleProcedure,
		svc.SetRule,
		connect.WithSchema(rulesMethods.ByName("SetRule")),
		connect.WithHandlerOptions(opts...),
	)
	rulesSetRuleStatusHandler := connect.NewUnaryHandler(
		RulesSetRuleStatusProcedure,
		svc.SetRuleStatus,
		connect.WithSchema(rulesMethods.ByName("SetRuleStatus")),
		connect.WithHandlerOptions(opts...),
	)
	rulesDeleteRuleHandler := connect.NewUnaryHandler(
		RulesDeleteRuleProcedure,
		svc.DeleteRule,
		connect.WithSchema(rulesMethods.ByName("DeleteRule")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephant.spell.Rules/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RulesListRulesProcedure:
			rulesListRulesHandler.ServeHTTP(w, r)
		case RulesGetRuleProcedure:
			rulesGetRuleHandler.ServeHTTP(w, r)
		case RulesSetRuleProcedure:
			rulesSetRuleHandler.ServeHTTP(w, r)
		case RulesSetRuleStatusProcedure:
			rulesSetRuleStatusHandler.ServeHTTP(w, r)
		case RulesDeleteRuleProcedure:
			rulesDeleteRuleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRulesHandler returns CodeUnimplemented from all methods.
type UnimplementedRulesHandler struct{}

func (UnimplementedRulesHandler) ListRules(context.Context, *connect.Request[spell.ListRulesRequest]) (*connect.Response[spell.ListRulesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Rules.ListRules is not implemented"))
}

func (UnimplementedRulesHandler) GetRule(context.Context, *connect.Request[spell.GetRuleRequest]) (*connect.Response[spell.GetRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Rules.GetRule is not implemented"))
}

func (UnimplementedRulesHandler) SetRule(context.Context, *connect.Request[spell.SetRuleRequest]) (*connect.Response[spell.SetRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Rules.SetRule is not implemented"))
}

func (UnimplementedRulesHandler) SetRuleStatus(context.Context, *connect.Request[spell.SetRuleStatusRequest]) (*connect.Response[spell.SetRuleStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Rules.SetRuleStatus is not implemented"))
}

func (UnimplementedRulesHandler) DeleteRule(context.Context, *connect.Request[spell.DeleteRuleRequest]) (*connect.Response[spell.DeleteRuleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.spell.Rules.DeleteRule is not implemented"))
}
