// Code generated by protoc-gen-elephant-rpc. DO NOT EDIT.
//
// Source: repository/service.proto

package repositoryconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	repository "github.com/ttab/elephant-api/repository"
	http "net/http"
)

// NewDocumentsServiceHandler builds an HTTP handler for the elephant.repository.Documents service
// from an implementation of the plain repository.Documents interface, and returns the path to mount
// it on together with the handler, just like NewDocumentsHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewDocumentsServiceHandler(svc repository.Documents, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewDocumentsHandler(&documentsServiceHandler{svc: svc}, opts...)
}

// documentsServiceHandler implements DocumentsHandler on top of a repository.Documents.
type documentsServiceHandler struct {
	svc repository.Documents
}

func (h *documentsServiceHandler) Get(ctx context.Context, req *connect.Request[repository.GetDocumentRequest]) (*connect.Response[repository.GetDocumentResponse], error) {
	res, err := h.svc.Get(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) BulkGet(ctx context.Context, req *connect.Request[repository.BulkGetRequest]) (*connect.Response[repository.BulkGetResponse], error) {
	res, err := h.svc.BulkGet(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetHistory(ctx context.Context, req *connect.Request[repository.GetHistoryRequest]) (*connect.Response[repository.GetHistoryResponse], error) {
	res, err := h.svc.GetHistory(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Update(ctx context.Context, req *connect.Request[repository.UpdateRequest]) (*connect.Response[repository.UpdateResponse], error) {
	res, err := h.svc.Update(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) BulkUpdate(ctx context.Context, req *connect.Request[repository.BulkUpdateRequest]) (*connect.Response[repository.BulkUpdateResponse], error) {
	res, err := h.svc.BulkUpdate(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Validate(ctx context.Context, req *connect.Request[repository.ValidateRequest]) (*connect.Response[repository.ValidateResponse], error) {
	res, err := h.svc.Validate(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Prune(ctx context.Context, req *connect.Request[repository.PruneRequest]) (*connect.Response[repository.PruneResponse], error) {
	res, err := h.svc.Prune(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Evict(ctx context.Context, req *connect.Request[repository.EvictRequest]) (*connect.Response[repository.EvictResponse], error) {
	res, err := h.svc.Evict(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Delete(ctx context.Context, req *connect.Request[repository.DeleteDocumentRequest]) (*connect.Response[repository.DeleteDocumentResponse], error) {
	res, err := h.svc.Delete(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) ListDeleted(ctx context.Context, req *connect.Request[repository.ListDeletedRequest]) (*connect.Response[repository.ListDeletedResponse], error) {
	res, err := h.svc.ListDeleted(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Restore(ctx context.Context, req *connect.Request[repository.RestoreRequest]) (*connect.Response[repository.RestoreResponse], error) {
	res, err := h.svc.Restore(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Purge(ctx context.Context, req *connect.Request[repository.PurgeRequest]) (*connect.Response[repository.PurgeResponse], error) {
	res, err := h.svc.Purge(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetMeta(ctx context.Context, req *connect.Request[repository.GetMetaRequest]) (*connect.Response[repository.GetMetaResponse], error) {
	res, err := h.svc.GetMeta(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Eventlog(ctx context.Context, req *connect.Request[repository.GetEventlogRequest]) (*connect.Response[repository.GetEventlogResponse], error) {
	res, err := h.svc.Eventlog(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) CompactedEventlog(ctx context.Context, req *connect.Request[repository.GetCompactedEventlogRequest]) (*connect.Response[repository.GetCompactedEventlogResponse], error) {
	res, err := h.svc.CompactedEventlog(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetStatus(ctx context.Context, req *connect.Request[repository.GetStatusRequest]) (*connect.Response[repository.GetStatusResponse], error) {
	res, err := h.svc.GetStatus(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetStatusHistory(ctx context.Context, req *connect.Request[repository.GetStatusHistoryRequest]) (*connect.Response[repository.GetStatusHistoryReponse], error) {
	res, err := h.svc.GetStatusHistory(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetNilStatuses(ctx context.Context, req *connect.Request[repository.GetNilStatusesRequest]) (*connect.Response[repository.GetNilStatusesResponse], error) {
	res, err := h.svc.GetNilStatuses(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetStatusOverview(ctx context.Context, req *connect.Request[repository.GetStatusOverviewRequest]) (*connect.Response[repository.GetStatusOverviewResponse], error) {
	res, err := h.svc.GetStatusOverview(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetPermissions(ctx context.Context, req *connect.Request[repository.GetPermissionsRequest]) (*connect.Response[repository.GetPermissionsResponse], error) {
	res, err := h.svc.GetPermissions(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Lock(ctx context.Context, req *connect.Request[repository.LockRequest]) (*connect.Response[repository.LockResponse], error) {
	res, err := h.svc.Lock(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) ExtendLock(ctx context.Context, req *connect.Request[repository.ExtendLockRequest]) (*connect.Response[repository.LockResponse], error) {
	res, err := h.svc.ExtendLock(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) Unlock(ctx context.Context, req *connect.Request[repository.UnlockRequest]) (*connect.Response[repository.UnlockResponse], error) {
	res, err := h.svc.Unlock(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetWithheld(ctx context.Context, req *connect.Request[repository.GetWithheldRequest]) (*connect.Response[repository.GetWithheldResponse], error) {
	res, err := h.svc.GetWithheld(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetDeliverableInfo(ctx context.Context, req *connect.Request[repository.GetDeliverableInfoRequest]) (*connect.Response[repository.GetDeliverableInfoResponse], error) {
	res, err := h.svc.GetDeliverableInfo(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) BulkGetDeliverableInfo(ctx context.Context, req *connect.Request[repository.BulkGetDeliverableInfoRequest]) (*connect.Response[repository.BulkGetDeliverableInfoResponse], error) {
	res, err := h.svc.BulkGetDeliverableInfo(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) CreateUpload(ctx context.Context, req *connect.Request[repository.CreateUploadRequest]) (*connect.Response[repository.CreateUploadResponse], error) {
	res, err := h.svc.CreateUpload(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetAttachments(ctx context.Context, req *connect.Request[repository.GetAttachmentsRequest]) (*connect.Response[repository.GetAttachmentsResponse], error) {
	res, err := h.svc.GetAttachments(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetMatching(ctx context.Context, req *connect.Request[repository.GetMatchingRequest]) (*connect.Response[repository.GetMatchingResponse], error) {
	res, err := h.svc.GetMatching(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *documentsServiceHandler) GetSocketToken(ctx context.Context, req *connect.Request[repository.GetSocketTokenRequest]) (*connect.Response[repository.GetSocketTokenResponse], error) {
	res, err := h.svc.GetSocketToken(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewDocumentsServiceClient constructs a client for the elephant.repository.Documents service that
// implements the plain repository.Documents interface, so that it is a drop-in for the Twirp
// clients. The options are the ones NewDocumentsClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewDocumentsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) repository.Documents {
	return &documentsServiceClient{
		client: NewDocumentsClient(httpClient, baseURL, opts...),
	}
}

// documentsServiceClient implements repository.Documents on top of a DocumentsClient.
type documentsServiceClient struct {
	client DocumentsClient
}

func (c *documentsServiceClient) Get(ctx context.Context, req *repository.GetDocumentRequest) (*repository.GetDocumentResponse, error) {
	res, err := c.client.Get(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) BulkGet(ctx context.Context, req *repository.BulkGetRequest) (*repository.BulkGetResponse, error) {
	res, err := c.client.BulkGet(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetHistory(ctx context.Context, req *repository.GetHistoryRequest) (*repository.GetHistoryResponse, error) {
	res, err := c.client.GetHistory(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Update(ctx context.Context, req *repository.UpdateRequest) (*repository.UpdateResponse, error) {
	res, err := c.client.Update(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) BulkUpdate(ctx context.Context, req *repository.BulkUpdateRequest) (*repository.BulkUpdateResponse, error) {
	res, err := c.client.BulkUpdate(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Validate(ctx context.Context, req *repository.ValidateRequest) (*repository.ValidateResponse, error) {
	res, err := c.client.Validate(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Prune(ctx context.Context, req *repository.PruneRequest) (*repository.PruneResponse, error) {
	res, err := c.client.Prune(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Evict(ctx context.Context, req *repository.EvictRequest) (*repository.EvictResponse, error) {
	res, err := c.client.Evict(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Delete(ctx context.Context, req *repository.DeleteDocumentRequest) (*repository.DeleteDocumentResponse, error) {
	res, err := c.client.Delete(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) ListDeleted(ctx context.Context, req *repository.ListDeletedRequest) (*repository.ListDeletedResponse, error) {
	res, err := c.client.ListDeleted(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Restore(ctx context.Context, req *repository.RestoreRequest) (*repository.RestoreResponse, error) {
	res, err := c.client.Restore(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Purge(ctx context.Context, req *repository.PurgeRequest) (*repository.PurgeResponse, error) {
	res, err := c.client.Purge(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetMeta(ctx context.Context, req *repository.GetMetaRequest) (*repository.GetMetaResponse, error) {
	res, err := c.client.GetMeta(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Eventlog(ctx context.Context, req *repository.GetEventlogRequest) (*repository.GetEventlogResponse, error) {
	res, err := c.client.Eventlog(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) CompactedEventlog(ctx context.Context, req *repository.GetCompactedEventlogRequest) (*repository.GetCompactedEventlogResponse, error) {
	res, err := c.client.CompactedEventlog(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetStatus(ctx context.Context, req *repository.GetStatusRequest) (*repository.GetStatusResponse, error) {
	res, err := c.client.GetStatus(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetStatusHistory(ctx context.Context, req *repository.GetStatusHistoryRequest) (*repository.GetStatusHistoryReponse, error) {
	res, err := c.client.GetStatusHistory(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetNilStatuses(ctx context.Context, req *repository.GetNilStatusesRequest) (*repository.GetNilStatusesResponse, error) {
	res, err := c.client.GetNilStatuses(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetStatusOverview(ctx context.Context, req *repository.GetStatusOverviewRequest) (*repository.GetStatusOverviewResponse, error) {
	res, err := c.client.GetStatusOverview(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetPermissions(ctx context.Context, req *repository.GetPermissionsRequest) (*repository.GetPermissionsResponse, error) {
	res, err := c.client.GetPermissions(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Lock(ctx context.Context, req *repository.LockRequest) (*repository.LockResponse, error) {
	res, err := c.client.Lock(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) ExtendLock(ctx context.Context, req *repository.ExtendLockRequest) (*repository.LockResponse, error) {
	res, err := c.client.ExtendLock(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) Unlock(ctx context.Context, req *repository.UnlockRequest) (*repository.UnlockResponse, error) {
	res, err := c.client.Unlock(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetWithheld(ctx context.Context, req *repository.GetWithheldRequest) (*repository.GetWithheldResponse, error) {
	res, err := c.client.GetWithheld(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetDeliverableInfo(ctx context.Context, req *repository.GetDeliverableInfoRequest) (*repository.GetDeliverableInfoResponse, error) {
	res, err := c.client.GetDeliverableInfo(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) BulkGetDeliverableInfo(ctx context.Context, req *repository.BulkGetDeliverableInfoRequest) (*repository.BulkGetDeliverableInfoResponse, error) {
	res, err := c.client.BulkGetDeliverableInfo(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) CreateUpload(ctx context.Context, req *repository.CreateUploadRequest) (*repository.CreateUploadResponse, error) {
	res, err := c.client.CreateUpload(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetAttachments(ctx context.Context, req *repository.GetAttachmentsRequest) (*repository.GetAttachmentsResponse, error) {
	res, err := c.client.GetAttachments(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetMatching(ctx context.Context, req *repository.GetMatchingRequest) (*repository.GetMatchingResponse, error) {
	res, err := c.client.GetMatching(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *documentsServiceClient) GetSocketToken(ctx context.Context, req *repository.GetSocketTokenRequest) (*repository.GetSocketTokenResponse, error) {
	res, err := c.client.GetSocketToken(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewSchemasServiceHandler builds an HTTP handler for the elephant.repository.Schemas service from
// an implementation of the plain repository.Schemas interface, and returns the path to mount it on
// together with the handler, just like NewSchemasHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewSchemasServiceHandler(svc repository.Schemas, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewSchemasHandler(&schemasServiceHandler{svc: svc}, opts...)
}

// schemasServiceHandler implements SchemasHandler on top of a repository.Schemas.
type schemasServiceHandler struct {
	svc repository.Schemas
}

func (h *schemasServiceHandler) RegisterGeneration(ctx context.Context, req *connect.Request[repository.RegisterGenerationRequest]) (*connect.Response[repository.RegisterGenerationResponse], error) {
	res, err := h.svc.RegisterGeneration(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) SetActive(ctx context.Context, req *connect.Request[repository.SetActiveSchemasRequest]) (*connect.Response[repository.SetActiveSchemasResponse], error) {
	res, err := h.svc.SetActive(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) ListGenerations(ctx context.Context, req *connect.Request[repository.ListSchemaGenerationsRequest]) (*connect.Response[repository.ListSchemaGenerationsResponse], error) {
	res, err := h.svc.ListGenerations(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) GetExemplars(ctx context.Context, req *connect.Request[repository.GetExemplarsRequest]) (*connect.Response[repository.GetExemplarsResponse], error) {
	res, err := h.svc.GetExemplars(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) Get(ctx context.Context, req *connect.Request[repository.GetSchemaRequest]) (*connect.Response[repository.GetSchemaResponse], error) {
	res, err := h.svc.Get(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) GetAllActive(ctx context.Context, req *connect.Request[repository.GetAllActiveSchemasRequest]) (*connect.Response[repository.GetAllActiveSchemasResponse], error) {
	res, err := h.svc.GetAllActive(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) ListActive(ctx context.Context, req *connect.Request[repository.ListActiveSchemasRequest]) (*connect.Response[repository.ListActiveSchemasResponse], error) {
	res, err := h.svc.ListActive(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) RegisterMetaType(ctx context.Context, req *connect.Request[repository.RegisterMetaTypeRequest]) (*connect.Response[repository.RegisterMetaTypeResponse], error) {
	res, err := h.svc.RegisterMetaType(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) RegisterMetaTypeUse(ctx context.Context, req *connect.Request[repository.RegisterMetaTypeUseRequest]) (*connect.Response[repository.RegisterMetaTypeUseResponse], error) {
	res, err := h.svc.RegisterMetaTypeUse(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) GetMetaTypes(ctx context.Context, req *connect.Request[repository.GetMetaTypesRequest]) (*connect.Response[repository.GetMetaTypesResponse], error) {
	res, err := h.svc.GetMetaTypes(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) GetDeprecations(ctx context.Context, req *connect.Request[repository.GetDeprecationsRequest]) (*connect.Response[repository.GetDeprecationsResponse], error) {
	res, err := h.svc.GetDeprecations(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) UpdateDeprecation(ctx context.Context, req *connect.Request[repository.UpdateDeprecationRequest]) (*connect.Response[repository.UpdateDeprecationResponse], error) {
	res, err := h.svc.UpdateDeprecation(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) GetDocumentTypes(ctx context.Context, req *connect.Request[repository.GetDocumentTypesRequest]) (*connect.Response[repository.GetDocumentTypesResponse], error) {
	res, err := h.svc.GetDocumentTypes(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) ConfigureType(ctx context.Context, req *connect.Request[repository.ConfigureTypeRequest]) (*connect.Response[repository.ConfigureTypeResponse], error) {
	res, err := h.svc.ConfigureType(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *schemasServiceHandler) GetTypeConfiguration(ctx context.Context, req *connect.Request[repository.GetTypeConfigurationRequest]) (*connect.Response[repository.GetTypeConfigurationResponse], error) {
	res, err := h.svc.GetTypeConfiguration(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewSchemasServiceClient constructs a client for the elephant.repository.Schemas service that
// implements the plain repository.Schemas interface, so that it is a drop-in for the Twirp clients.
// The options are the ones NewSchemasClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewSchemasServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) repository.Schemas {
	return &schemasServiceClient{
		client: NewSchemasClient(httpClient, baseURL, opts...),
	}
}

// schemasServiceClient implements repository.Schemas on top of a SchemasClient.
type schemasServiceClient struct {
	client SchemasClient
}

func (c *schemasServiceClient) RegisterGeneration(ctx context.Context, req *repository.RegisterGenerationRequest) (*repository.RegisterGenerationResponse, error) {
	res, err := c.client.RegisterGeneration(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) SetActive(ctx context.Context, req *repository.SetActiveSchemasRequest) (*repository.SetActiveSchemasResponse, error) {
	res, err := c.client.SetActive(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) ListGenerations(ctx context.Context, req *repository.ListSchemaGenerationsRequest) (*repository.ListSchemaGenerationsResponse, error) {
	res, err := c.client.ListGenerations(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) GetExemplars(ctx context.Context, req *repository.GetExemplarsRequest) (*repository.GetExemplarsResponse, error) {
	res, err := c.client.GetExemplars(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) Get(ctx context.Context, req *repository.GetSchemaRequest) (*repository.GetSchemaResponse, error) {
	res, err := c.client.Get(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) GetAllActive(ctx context.Context, req *repository.GetAllActiveSchemasRequest) (*repository.GetAllActiveSchemasResponse, error) {
	res, err := c.client.GetAllActive(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) ListActive(ctx context.Context, req *repository.ListActiveSchemasRequest) (*repository.ListActiveSchemasResponse, error) {
	res, err := c.client.ListActive(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) RegisterMetaType(ctx context.Context, req *repository.RegisterMetaTypeRequest) (*repository.RegisterMetaTypeResponse, error) {
	res, err := c.client.RegisterMetaType(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) RegisterMetaTypeUse(ctx context.Context, req *repository.RegisterMetaTypeUseRequest) (*repository.RegisterMetaTypeUseResponse, error) {
	res, err := c.client.RegisterMetaTypeUse(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) GetMetaTypes(ctx context.Context, req *repository.GetMetaTypesRequest) (*repository.GetMetaTypesResponse, error) {
	res, err := c.client.GetMetaTypes(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) GetDeprecations(ctx context.Context, req *repository.GetDeprecationsRequest) (*repository.GetDeprecationsResponse, error) {
	res, err := c.client.GetDeprecations(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) UpdateDeprecation(ctx context.Context, req *repository.UpdateDeprecationRequest) (*repository.UpdateDeprecationResponse, error) {
	res, err := c.client.UpdateDeprecation(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) GetDocumentTypes(ctx context.Context, req *repository.GetDocumentTypesRequest) (*repository.GetDocumentTypesResponse, error) {
	res, err := c.client.GetDocumentTypes(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) ConfigureType(ctx context.Context, req *repository.ConfigureTypeRequest) (*repository.ConfigureTypeResponse, error) {
	res, err := c.client.ConfigureType(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *schemasServiceClient) GetTypeConfiguration(ctx context.Context, req *repository.GetTypeConfigurationRequest) (*repository.GetTypeConfigurationResponse, error) {
	res, err := c.client.GetTypeConfiguration(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewWorkflowsServiceHandler builds an HTTP handler for the elephant.repository.Workflows service
// from an implementation of the plain repository.Workflows interface, and returns the path to mount
// it on together with the handler, just like NewWorkflowsHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewWorkflowsServiceHandler(svc repository.Workflows, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewWorkflowsHandler(&workflowsServiceHandler{svc: svc}, opts...)
}

// workflowsServiceHandler implements WorkflowsHandler on top of a repository.Workflows.
type workflowsServiceHandler struct {
	svc repository.Workflows
}

func (h *workflowsServiceHandler) UpdateStatus(ctx context.Context, req *connect.Request[repository.UpdateStatusRequest]) (*connect.Response[repository.UpdateStatusResponse], error) {
	res, err := h.svc.UpdateStatus(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *workflowsServiceHandler) GetStatuses(ctx context.Context, req *connect.Request[repository.GetStatusesRequest]) (*connect.Response[repository.GetStatusesResponse], error) {
	res, err := h.svc.GetStatuses(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *workflowsServiceHandler) CreateStatusRule(ctx context.Context, req *connect.Request[repository.CreateStatusRuleRequest]) (*connect.Response[repository.CreateStatusRuleResponse], error) {
	res, err := h.svc.CreateStatusRule(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *workflowsServiceHandler) DeleteStatusRule(ctx context.Context, req *connect.Request[repository.DeleteStatusRuleRequest]) (*connect.Response[repository.DeleteStatusRuleResponse], error) {
	res, err := h.svc.DeleteStatusRule(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *workflowsServiceHandler) GetStatusRules(ctx context.Context, req *connect.Request[repository.GetStatusRulesRequest]) (*connect.Response[repository.GetStatusRulesResponse], error) {
	res, err := h.svc.GetStatusRules(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *workflowsServiceHandler) SetWorkflow(ctx context.Context, req *connect.Request[repository.SetWorkflowRequest]) (*connect.Response[repository.SetWorkflowResponse], error) {
	res, err := h.svc.SetWorkflow(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *workflowsServiceHandler) GetWorkflow(ctx context.Context, req *connect.Request[repository.GetWorkflowRequest]) (*connect.Response[repository.GetWorkflowResponse], error) {
	res, err := h.svc.GetWorkflow(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *workflowsServiceHandler) DeleteWorkflow(ctx context.Context, req *connect.Request[repository.DeleteWorkflowRequest]) (*connect.Response[repository.DeleteWorkflowResponse], error) {
	res, err := h.svc.DeleteWorkflow(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewWorkflowsServiceClient constructs a client for the elephant.repository.Workflows service that
// implements the plain repository.Workflows interface, so that it is a drop-in for the Twirp
// clients. The options are the ones NewWorkflowsClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewWorkflowsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) repository.Workflows {
	return &workflowsServiceClient{
		client: NewWorkflowsClient(httpClient, baseURL, opts...),
	}
}

// workflowsServiceClient implements repository.Workflows on top of a WorkflowsClient.
type workflowsServiceClient struct {
	client WorkflowsClient
}

func (c *workflowsServiceClient) UpdateStatus(ctx context.Context, req *repository.UpdateStatusRequest) (*repository.UpdateStatusResponse, error) {
	res, err := c.client.UpdateStatus(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *workflowsServiceClient) GetStatuses(ctx context.Context, req *repository.GetStatusesRequest) (*repository.GetStatusesResponse, error) {
	res, err := c.client.GetStatuses(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *workflowsServiceClient) CreateStatusRule(ctx context.Context, req *repository.CreateStatusRuleRequest) (*repository.CreateStatusRuleResponse, error) {
	res, err := c.client.CreateStatusRule(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *workflowsServiceClient) DeleteStatusRule(ctx context.Context, req *repository.DeleteStatusRuleRequest) (*repository.DeleteStatusRuleResponse, error) {
	res, err := c.client.DeleteStatusRule(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *workflowsServiceClient) GetStatusRules(ctx context.Context, req *repository.GetStatusRulesRequest) (*repository.GetStatusRulesResponse, error) {
	res, err := c.client.GetStatusRules(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *workflowsServiceClient) SetWorkflow(ctx context.Context, req *repository.SetWorkflowRequest) (*repository.SetWorkflowResponse, error) {
	res, err := c.client.SetWorkflow(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *workflowsServiceClient) GetWorkflow(ctx context.Context, req *repository.GetWorkflowRequest) (*repository.GetWorkflowResponse, error) {
	res, err := c.client.GetWorkflow(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *workflowsServiceClient) DeleteWorkflow(ctx context.Context, req *repository.DeleteWorkflowRequest) (*repository.DeleteWorkflowResponse, error) {
	res, err := c.client.DeleteWorkflow(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

// NewMetricsServiceHandler builds an HTTP handler for the elephant.repository.Metrics service from
// an implementation of the plain repository.Metrics interface, and returns the path to mount it on
// together with the handler, just like NewMetricsHandler does.
//
// Errors from the implementation are passed through untouched, so an implementation that wants to
// control the response code returns a *connect.Error.
func NewMetricsServiceHandler(svc repository.Metrics, opts ...connect.HandlerOption) (string, http.Handler) {
	return NewMetricsHandler(&metricsServiceHandler{svc: svc}, opts...)
}

// metricsServiceHandler implements MetricsHandler on top of a repository.Metrics.
type metricsServiceHandler struct {
	svc repository.Metrics
}

func (h *metricsServiceHandler) RegisterKind(ctx context.Context, req *connect.Request[repository.RegisterMetricKindRequest]) (*connect.Response[repository.RegisterMetricKindResponse], error) {
	res, err := h.svc.RegisterKind(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *metricsServiceHandler) DeleteKind(ctx context.Context, req *connect.Request[repository.DeleteMetricKindRequest]) (*connect.Response[repository.DeleteMetricKindResponse], error) {
	res, err := h.svc.DeleteKind(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *metricsServiceHandler) GetKinds(ctx context.Context, req *connect.Request[repository.GetMetricKindsRequest]) (*connect.Response[repository.GetMetricKindsResponse], error) {
	res, err := h.svc.GetKinds(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *metricsServiceHandler) RegisterMetric(ctx context.Context, req *connect.Request[repository.RegisterMetricRequest]) (*connect.Response[repository.RegisterMetricResponse], error) {
	res, err := h.svc.RegisterMetric(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

func (h *metricsServiceHandler) GetMetrics(ctx context.Context, req *connect.Request[repository.GetMetricsRequest]) (*connect.Response[repository.GetMetricsResponse], error) {
	res, err := h.svc.GetMetrics(ctx, req.Msg)
	if err != nil {
		return nil, err
	}

	return connect.NewResponse(res), nil
}

// NewMetricsServiceClient constructs a client for the elephant.repository.Metrics service that
// implements the plain repository.Metrics interface, so that it is a drop-in for the Twirp clients.
// The options are the ones NewMetricsClient takes.
//
// The base URL is the base URL of the Connect or gRPC server, for example
// https://repository.api.tt.se. Errors are returned as the *connect.Error values the Connect client
// produces.
func NewMetricsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) repository.Metrics {
	return &metricsServiceClient{
		client: NewMetricsClient(httpClient, baseURL, opts...),
	}
}

// metricsServiceClient implements repository.Metrics on top of a MetricsClient.
type metricsServiceClient struct {
	client MetricsClient
}

func (c *metricsServiceClient) RegisterKind(ctx context.Context, req *repository.RegisterMetricKindRequest) (*repository.RegisterMetricKindResponse, error) {
	res, err := c.client.RegisterKind(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *metricsServiceClient) DeleteKind(ctx context.Context, req *repository.DeleteMetricKindRequest) (*repository.DeleteMetricKindResponse, error) {
	res, err := c.client.DeleteKind(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *metricsServiceClient) GetKinds(ctx context.Context, req *repository.GetMetricKindsRequest) (*repository.GetMetricKindsResponse, error) {
	res, err := c.client.GetKinds(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *metricsServiceClient) RegisterMetric(ctx context.Context, req *repository.RegisterMetricRequest) (*repository.RegisterMetricResponse, error) {
	res, err := c.client.RegisterMetric(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}

func (c *metricsServiceClient) GetMetrics(ctx context.Context, req *repository.GetMetricsRequest) (*repository.GetMetricsResponse, error) {
	res, err := c.client.GetMetrics(ctx, connect.NewRequest(req))
	if err != nil {
		return nil, err
	}

	return res.Msg, nil
}
