// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: repositorysocket/service.proto

package repositorysocket

import (
	newsdoc "github.com/ttab/elephant-api/newsdoc"
	repository "github.com/ttab/elephant-api/repository"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Call struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CallID uniquely identifies this call and will be referenced in the
	// response.
	CallId           string            `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Authenticate     *Authenticate     `protobuf:"bytes,2,opt,name=authenticate,proto3" json:"authenticate,omitempty"`
	GetDocuments     *GetDocuments     `protobuf:"bytes,3,opt,name=get_documents,json=getDocuments,proto3" json:"get_documents,omitempty"`
	CloseDocumentSet *CloseDocumentSet `protobuf:"bytes,4,opt,name=close_document_set,json=closeDocumentSet,proto3" json:"close_document_set,omitempty"`
	GetEventlog      *GetEventlog      `protobuf:"bytes,5,opt,name=get_eventlog,json=getEventlog,proto3" json:"get_eventlog,omitempty"`
	CloseEventlog    *CloseEventlog    `protobuf:"bytes,6,opt,name=close_eventlog,json=closeEventlog,proto3" json:"close_eventlog,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_repositorysocket_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{0}
}

func (x *Call) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Call) GetAuthenticate() *Authenticate {
	if x != nil {
		return x.Authenticate
	}
	return nil
}

func (x *Call) GetGetDocuments() *GetDocuments {
	if x != nil {
		return x.GetDocuments
	}
	return nil
}

func (x *Call) GetCloseDocumentSet() *CloseDocumentSet {
	if x != nil {
		return x.CloseDocumentSet
	}
	return nil
}

func (x *Call) GetGetEventlog() *GetEventlog {
	if x != nil {
		return x.GetEventlog
	}
	return nil
}

func (x *Call) GetCloseEventlog() *CloseEventlog {
	if x != nil {
		return x.CloseEventlog
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CallID is the ID of the call that this is a response to.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Error is set if the call failed.
	Error          *Error           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DocumentBatch  *DocumentBatch   `protobuf:"bytes,3,opt,name=document_batch,json=documentBatch,proto3" json:"document_batch,omitempty"`
	DocumentUpdate *DocumentUpdate  `protobuf:"bytes,4,opt,name=document_update,json=documentUpdate,proto3" json:"document_update,omitempty"`
	InclusionBatch *InclusionBatch  `protobuf:"bytes,5,opt,name=inclusion_batch,json=inclusionBatch,proto3" json:"inclusion_batch,omitempty"`
	Removed        *DocumentRemoved `protobuf:"bytes,6,opt,name=removed,proto3" json:"removed,omitempty"`
	// Handled is true when the call has been completely handled without
	// errors. For calls that create subscriptions this means that the
	// subscription has been created successfully.
	Handled bool `protobuf:"varint,7,opt,name=handled,proto3" json:"handled,omitempty"`
	// Events from the eventlog.
	Events        *EventlogResponse `protobuf:"bytes,8,opt,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_repositorysocket_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetDocumentBatch() *DocumentBatch {
	if x != nil {
		return x.DocumentBatch
	}
	return nil
}

func (x *Response) GetDocumentUpdate() *DocumentUpdate {
	if x != nil {
		return x.DocumentUpdate
	}
	return nil
}

func (x *Response) GetInclusionBatch() *InclusionBatch {
	if x != nil {
		return x.InclusionBatch
	}
	return nil
}

func (x *Response) GetRemoved() *DocumentRemoved {
	if x != nil {
		return x.Removed
	}
	return nil
}

func (x *Response) GetHandled() bool {
	if x != nil {
		return x.Handled
	}
	return false
}

func (x *Response) GetEvents() *EventlogResponse {
	if x != nil {
		return x.Events
	}
	return nil
}

// Error is used to communicate errors.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ErrorCode classifying the error.
	ErrorCode string `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	// ErrorMessage describing the error.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_repositorysocket_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Error) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Authenticate is used to authenticate a connection. The socket will be closed
// if the client fails to reauthenticate before the token expires. The socket
// will also be closed if the user sub changes between authenticate calls.
//
// Responds with RespSuccess if the connection is successfully authenticated.
type Authenticate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticate) Reset() {
	*x = Authenticate{}
	mi := &file_repositorysocket_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticate) ProtoMessage() {}

func (x *Authenticate) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticate.ProtoReflect.Descriptor instead.
func (*Authenticate) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{3}
}

func (x *Authenticate) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetEventlog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the eventlog subscription. Opening an eventlog subscription with
	// the same name as an existing subscription will close the existing
	// subscription. This can be used together with `from` to update a
	// subscription without missing events.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// After allows the client to subscribe from after a given event ID. The
	// server only buffers a limited amount of events (defaults to 500) and
	// requesting events from before the range of that buffer will result in a
	// resume out of bounds "eventlog_resume_oob" error.
	After *int64 `protobuf:"varint,2,opt,name=after,proto3,oneof" json:"after,omitempty"`
	// DocumentTypes for which the client wants events for. If no types are
	// provided all types will be included.
	DocumentTypes []string `protobuf:"bytes,3,rep,name=document_types,json=documentTypes,proto3" json:"document_types,omitempty"`
	// Languages that the client wants events for. If no languages are provided
	// all languages will be included. If a document switches language the event for
	// the switch will be included even if the new document version doesn't have a
	// matching language anymore.
	Languages []string `protobuf:"bytes,4,rep,name=languages,proto3" json:"languages,omitempty"`
	// TypeSubsets are used to apply subset newsdoc value extractors to documents
	// and include the results with the event data. Keyed by document type.
	TypeSubsets map[string]*Subsets `protobuf:"bytes,5,rep,name=type_subsets,json=typeSubsets,proto3" json:"type_subsets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Events are the event types the client wants events for, one of: "document",
	// "status", "acl", "delete_document", "restore_finished", "workflow". If no
	// event types are provided all event types will be included.
	Events        []string `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventlog) Reset() {
	*x = GetEventlog{}
	mi := &file_repositorysocket_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventlog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventlog) ProtoMessage() {}

func (x *GetEventlog) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventlog.ProtoReflect.Descriptor instead.
func (*GetEventlog) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventlog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEventlog) GetAfter() int64 {
	if x != nil && x.After != nil {
		return *x.After
	}
	return 0
}

func (x *GetEventlog) GetDocumentTypes() []string {
	if x != nil {
		return x.DocumentTypes
	}
	return nil
}

func (x *GetEventlog) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *GetEventlog) GetTypeSubsets() map[string]*Subsets {
	if x != nil {
		return x.TypeSubsets
	}
	return nil
}

func (x *GetEventlog) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type Subsets struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Expressions to use to extract document contents.
	Expressions   []string `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subsets) Reset() {
	*x = Subsets{}
	mi := &file_repositorysocket_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subsets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subsets) ProtoMessage() {}

func (x *Subsets) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subsets.ProtoReflect.Descriptor instead.
func (*Subsets) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{5}
}

func (x *Subsets) GetExpressions() []string {
	if x != nil {
		return x.Expressions
	}
	return nil
}

type EventlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EventlogItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventlogResponse) Reset() {
	*x = EventlogResponse{}
	mi := &file_repositorysocket_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventlogResponse) ProtoMessage() {}

func (x *EventlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventlogResponse.ProtoReflect.Descriptor instead.
func (*EventlogResponse) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{6}
}

func (x *EventlogResponse) GetItems() []*EventlogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type EventlogItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event from the eventlog.
	Event *repository.EventlogItem `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Subset is the extracted subset of the document. Only provided if this is a
	// document event and subset expressions have been defined for the type.
	Subset        []*repository.ExtractedValues `protobuf:"bytes,2,rep,name=subset,proto3" json:"subset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventlogItem) Reset() {
	*x = EventlogItem{}
	mi := &file_repositorysocket_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventlogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventlogItem) ProtoMessage() {}

func (x *EventlogItem) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventlogItem.ProtoReflect.Descriptor instead.
func (*EventlogItem) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{7}
}

func (x *EventlogItem) GetEvent() *repository.EventlogItem {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventlogItem) GetSubset() []*repository.ExtractedValues {
	if x != nil {
		return x.Subset
	}
	return nil
}

type CloseEventlog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the eventlog subscription to close.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseEventlog) Reset() {
	*x = CloseEventlog{}
	mi := &file_repositorysocket_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseEventlog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseEventlog) ProtoMessage() {}

func (x *CloseEventlog) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseEventlog.ProtoReflect.Descriptor instead.
func (*CloseEventlog) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{8}
}

func (x *CloseEventlog) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetDocuments is used to fetch and optionally subscribe to a set of documents.
//
// Responds with a series of RespGetDocumentsBatch followed by
// RespDocumentUpdate as changes occur.
type GetDocuments struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SetName is the name of the document set. Required when subscribing.
	SetName string `protobuf:"bytes,1,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	// Type of the documents to get.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Timespan is the inclusive time range to get documents for. Optional, this
	// is only available for document types with time expressions and/or
	// deliverables.
	Timespan *repository.Timespan `protobuf:"bytes,3,opt,name=timespan,proto3" json:"timespan,omitempty"`
	// Labels are the labels that the documents must match.
	Labels []string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	// Filter to apply to the documents.
	Filter *repository.DocumentFilter `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	// Include will include documents with an UUID that matches the uuid of the
	// newdoc extraction expression. Timespans, labels and filters will not be
	// applied to included documents.
	Include []string `protobuf:"bytes,6,rep,name=include,proto3" json:"include,omitempty"`
	// IncludeACLs should be set to true to include ACL update events in the
	// stream of updates.
	IncludeAcls bool `protobuf:"varint,7,opt,name=include_acls,json=includeAcls,proto3" json:"include_acls,omitempty"`
	// Subset returns a subset of the document as specified by a list of newsdoc
	// value extractors.
	Subset []string `protobuf:"bytes,8,rep,name=subset,proto3" json:"subset,omitempty"`
	// InclusionSubsets are used to apply subset newsdoc value extractors to
	// included documents. Keyed by document type.
	InclusionSubsets map[string]*Subsets `protobuf:"bytes,9,rep,name=inclusion_subsets,json=inclusionSubsets,proto3" json:"inclusion_subsets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetDocuments) Reset() {
	*x = GetDocuments{}
	mi := &file_repositorysocket_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocuments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocuments) ProtoMessage() {}

func (x *GetDocuments) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocuments.ProtoReflect.Descriptor instead.
func (*GetDocuments) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetDocuments) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *GetDocuments) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetDocuments) GetTimespan() *repository.Timespan {
	if x != nil {
		return x.Timespan
	}
	return nil
}

func (x *GetDocuments) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GetDocuments) GetFilter() *repository.DocumentFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetDocuments) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *GetDocuments) GetIncludeAcls() bool {
	if x != nil {
		return x.IncludeAcls
	}
	return false
}

func (x *GetDocuments) GetSubset() []string {
	if x != nil {
		return x.Subset
	}
	return nil
}

func (x *GetDocuments) GetInclusionSubsets() map[string]*Subsets {
	if x != nil {
		return x.InclusionSubsets
	}
	return nil
}

// CloseDocumentSet is used to stop recieving updates for a document set.
//
// Responds with RespSuccess if the set was closed, or error code 'not_found' if
// the document set is unknown.
type CloseDocumentSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SetName is the name of the document set to close.
	SetName       string `protobuf:"bytes,1,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseDocumentSet) Reset() {
	*x = CloseDocumentSet{}
	mi := &file_repositorysocket_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseDocumentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseDocumentSet) ProtoMessage() {}

func (x *CloseDocumentSet) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseDocumentSet.ProtoReflect.Descriptor instead.
func (*CloseDocumentSet) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{10}
}

func (x *CloseDocumentSet) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

// DocumentBatch is emitted in response to a CallGetDocuments message. Multiple
// batch messages can be emitted for a single get documents call.
type DocumentBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SetName is the name of the set that result is for.
	SetName string `protobuf:"bytes,1,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	// Documents is a batch of documents that are included in the set.
	Documents []*DocumentState `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	// FinalBatch is set to true for the last batch in the response.
	FinalBatch    bool `protobuf:"varint,3,opt,name=final_batch,json=finalBatch,proto3" json:"final_batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentBatch) Reset() {
	*x = DocumentBatch{}
	mi := &file_repositorysocket_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentBatch) ProtoMessage() {}

func (x *DocumentBatch) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentBatch.ProtoReflect.Descriptor instead.
func (*DocumentBatch) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{11}
}

func (x *DocumentBatch) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *DocumentBatch) GetDocuments() []*DocumentState {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *DocumentBatch) GetFinalBatch() bool {
	if x != nil {
		return x.FinalBatch
	}
	return false
}

type DocumentState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Meta information about the document.
	Meta *repository.DocumentMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	// Document is the document itself.
	Document *newsdoc.Document `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	// Subset is the extracted subset of the document.
	Subset []*repository.ExtractedValues `protobuf:"bytes,3,rep,name=subset,proto3" json:"subset,omitempty"`
	// UUID of the document.
	Uuid          string `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentState) Reset() {
	*x = DocumentState{}
	mi := &file_repositorysocket_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentState) ProtoMessage() {}

func (x *DocumentState) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentState.ProtoReflect.Descriptor instead.
func (*DocumentState) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{12}
}

func (x *DocumentState) GetMeta() *repository.DocumentMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DocumentState) GetDocument() *newsdoc.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *DocumentState) GetSubset() []*repository.ExtractedValues {
	if x != nil {
		return x.Subset
	}
	return nil
}

func (x *DocumentState) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// DocumentUpdate is emitted when a write operation has affected a document in a
// set.
type DocumentUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SetName is the name of the set that result is for.
	SetName string `protobuf:"bytes,1,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	// Event is the change event for the document.
	Event *repository.EventlogItem `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// Meta information about the document, only included if the document is newly
	// added to the document set.
	Meta *repository.DocumentMeta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	// Document is included for document update events or if the document is newly
	// added to the document set.
	Document *newsdoc.Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	// Included is true if the update is for a document that was added through
	// inclusion.
	Included bool `protobuf:"varint,5,opt,name=included,proto3" json:"included,omitempty"`
	// Subset is the extracted subset of the document.
	Subset        []*repository.ExtractedValues `protobuf:"bytes,6,rep,name=subset,proto3" json:"subset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUpdate) Reset() {
	*x = DocumentUpdate{}
	mi := &file_repositorysocket_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUpdate) ProtoMessage() {}

func (x *DocumentUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUpdate.ProtoReflect.Descriptor instead.
func (*DocumentUpdate) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{13}
}

func (x *DocumentUpdate) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *DocumentUpdate) GetEvent() *repository.EventlogItem {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *DocumentUpdate) GetMeta() *repository.DocumentMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DocumentUpdate) GetDocument() *newsdoc.Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *DocumentUpdate) GetIncluded() bool {
	if x != nil {
		return x.Included
	}
	return false
}

func (x *DocumentUpdate) GetSubset() []*repository.ExtractedValues {
	if x != nil {
		return x.Subset
	}
	return nil
}

// DocumentRemoved is emitted when a document is removed from the set.
type DocumentRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SetName       string                 `protobuf:"bytes,1,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	DocumentUuid  string                 `protobuf:"bytes,2,opt,name=document_uuid,json=documentUuid,proto3" json:"document_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentRemoved) Reset() {
	*x = DocumentRemoved{}
	mi := &file_repositorysocket_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentRemoved) ProtoMessage() {}

func (x *DocumentRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentRemoved.ProtoReflect.Descriptor instead.
func (*DocumentRemoved) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{14}
}

func (x *DocumentRemoved) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *DocumentRemoved) GetDocumentUuid() string {
	if x != nil {
		return x.DocumentUuid
	}
	return ""
}

// InclusionBatch is emitted when documents are first included by documents in
// the set.
type InclusionBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SetName is the name of the set that result is for.
	SetName string `protobuf:"bytes,1,opt,name=set_name,json=setName,proto3" json:"set_name,omitempty"`
	// Documents is a batch of documents that are included in the set.
	Documents     []*InclusionDocument `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusionBatch) Reset() {
	*x = InclusionBatch{}
	mi := &file_repositorysocket_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionBatch) ProtoMessage() {}

func (x *InclusionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionBatch.ProtoReflect.Descriptor instead.
func (*InclusionBatch) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{15}
}

func (x *InclusionBatch) GetSetName() string {
	if x != nil {
		return x.SetName
	}
	return ""
}

func (x *InclusionBatch) GetDocuments() []*InclusionDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

// InclusionDocument is a document that was referenced by a document in the set.
type InclusionDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	State         *DocumentState         `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusionDocument) Reset() {
	*x = InclusionDocument{}
	mi := &file_repositorysocket_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionDocument) ProtoMessage() {}

func (x *InclusionDocument) ProtoReflect() protoreflect.Message {
	mi := &file_repositorysocket_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionDocument.ProtoReflect.Descriptor instead.
func (*InclusionDocument) Descriptor() ([]byte, []int) {
	return file_repositorysocket_service_proto_rawDescGZIP(), []int{16}
}

func (x *InclusionDocument) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *InclusionDocument) GetState() *DocumentState {
	if x != nil {
		return x.State
	}
	return nil
}

var File_repositorysocket_service_proto protoreflect.FileDescriptor

const file_repositorysocket_service_proto_rawDesc = "" +
	"\n" +
	"\x1erepositorysocket/service.proto\x12\x19elephant.repositorysocket\x1a\x15newsdoc/newsdoc.proto\x1a\x18repository/service.proto\"\xb1\x03\n" +
	"\x04Call\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12K\n" +
	"\fauthenticate\x18\x02 \x01(\v2'.elephant.repositorysocket.AuthenticateR\fauthenticate\x12L\n" +
	"\rget_documents\x18\x03 \x01(\v2'.elephant.repositorysocket.GetDocumentsR\fgetDocuments\x12Y\n" +
	"\x12close_document_set\x18\x04 \x01(\v2+.elephant.repositorysocket.CloseDocumentSetR\x10closeDocumentSet\x12I\n" +
	"\fget_eventlog\x18\x05 \x01(\v2&.elephant.repositorysocket.GetEventlogR\vgetEventlog\x12O\n" +
	"\x0eclose_eventlog\x18\x06 \x01(\v2(.elephant.repositorysocket.CloseEventlogR\rcloseEventlog\"\xf9\x03\n" +
	"\bResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x126\n" +
	"\x05error\x18\x02 \x01(\v2 .elephant.repositorysocket.ErrorR\x05error\x12O\n" +
	"\x0edocument_batch\x18\x03 \x01(\v2(.elephant.repositorysocket.DocumentBatchR\rdocumentBatch\x12R\n" +
	"\x0fdocument_update\x18\x04 \x01(\v2).elephant.repositorysocket.DocumentUpdateR\x0edocumentUpdate\x12R\n" +
	"\x0finclusion_batch\x18\x05 \x01(\v2).elephant.repositorysocket.InclusionBatchR\x0einclusionBatch\x12D\n" +
	"\aremoved\x18\x06 \x01(\v2*.elephant.repositorysocket.DocumentRemovedR\aremoved\x12\x18\n" +
	"\ahandled\x18\a \x01(\bR\ahandled\x12C\n" +
	"\x06events\x18\b \x01(\v2+.elephant.repositorysocket.EventlogResponseR\x06events\"K\n" +
	"\x05Error\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"$\n" +
	"\fAuthenticate\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\xe3\x02\n" +
	"\vGetEventlog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\x05after\x18\x02 \x01(\x03H\x00R\x05after\x88\x01\x01\x12%\n" +
	"\x0edocument_types\x18\x03 \x03(\tR\rdocumentTypes\x12\x1c\n" +
	"\tlanguages\x18\x04 \x03(\tR\tlanguages\x12Z\n" +
	"\ftype_subsets\x18\x05 \x03(\v27.elephant.repositorysocket.GetEventlog.TypeSubsetsEntryR\vtypeSubsets\x12\x16\n" +
	"\x06events\x18\x06 \x03(\tR\x06events\x1ab\n" +
	"\x10TypeSubsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".elephant.repositorysocket.SubsetsR\x05value:\x028\x01B\b\n" +
	"\x06_after\"+\n" +
	"\aSubsets\x12 \n" +
	"\vexpressions\x18\x01 \x03(\tR\vexpressions\"Q\n" +
	"\x10EventlogResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.elephant.repositorysocket.EventlogItemR\x05items\"\x85\x01\n" +
	"\fEventlogItem\x127\n" +
	"\x05event\x18\x01 \x01(\v2!.elephant.repository.EventlogItemR\x05event\x12<\n" +
	"\x06subset\x18\x02 \x03(\v2$.elephant.repository.ExtractedValuesR\x06subset\"#\n" +
	"\rCloseEventlog\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xf7\x03\n" +
	"\fGetDocuments\x12\x19\n" +
	"\bset_name\x18\x01 \x01(\tR\asetName\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x129\n" +
	"\btimespan\x18\x03 \x01(\v2\x1d.elephant.repository.TimespanR\btimespan\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x12;\n" +
	"\x06filter\x18\x05 \x01(\v2#.elephant.repository.DocumentFilterR\x06filter\x12\x18\n" +
	"\ainclude\x18\x06 \x03(\tR\ainclude\x12!\n" +
	"\finclude_acls\x18\a \x01(\bR\vincludeAcls\x12\x16\n" +
	"\x06subset\x18\b \x03(\tR\x06subset\x12j\n" +
	"\x11inclusion_subsets\x18\t \x03(\v2=.elephant.repositorysocket.GetDocuments.InclusionSubsetsEntryR\x10inclusionSubsets\x1ag\n" +
	"\x15InclusionSubsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".elephant.repositorysocket.SubsetsR\x05value:\x028\x01\"-\n" +
	"\x10CloseDocumentSet\x12\x19\n" +
	"\bset_name\x18\x01 \x01(\tR\asetName\"\x93\x01\n" +
	"\rDocumentBatch\x12\x19\n" +
	"\bset_name\x18\x01 \x01(\tR\asetName\x12F\n" +
	"\tdocuments\x18\x02 \x03(\v2(.elephant.repositorysocket.DocumentStateR\tdocuments\x12\x1f\n" +
	"\vfinal_batch\x18\x03 \x01(\bR\n" +
	"finalBatch\"\xc7\x01\n" +
	"\rDocumentState\x125\n" +
	"\x04meta\x18\x01 \x01(\v2!.elephant.repository.DocumentMetaR\x04meta\x12-\n" +
	"\bdocument\x18\x02 \x01(\v2\x11.newsdoc.DocumentR\bdocument\x12<\n" +
	"\x06subset\x18\x03 \x03(\v2$.elephant.repository.ExtractedValuesR\x06subset\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\"\xa4\x02\n" +
	"\x0eDocumentUpdate\x12\x19\n" +
	"\bset_name\x18\x01 \x01(\tR\asetName\x127\n" +
	"\x05event\x18\x02 \x01(\v2!.elephant.repository.EventlogItemR\x05event\x125\n" +
	"\x04meta\x18\x03 \x01(\v2!.elephant.repository.DocumentMetaR\x04meta\x12-\n" +
	"\bdocument\x18\x04 \x01(\v2\x11.newsdoc.DocumentR\bdocument\x12\x1a\n" +
	"\bincluded\x18\x05 \x01(\bR\bincluded\x12<\n" +
	"\x06subset\x18\x06 \x03(\v2$.elephant.repository.ExtractedValuesR\x06subset\"Q\n" +
	"\x0fDocumentRemoved\x12\x19\n" +
	"\bset_name\x18\x01 \x01(\tR\asetName\x12#\n" +
	"\rdocument_uuid\x18\x02 \x01(\tR\fdocumentUuid\"w\n" +
	"\x0eInclusionBatch\x12\x19\n" +
	"\bset_name\x18\x01 \x01(\tR\asetName\x12J\n" +
	"\tdocuments\x18\x02 \x03(\v2,.elephant.repositorysocket.InclusionDocumentR\tdocuments\"g\n" +
	"\x11InclusionDocument\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12>\n" +
	"\x05state\x18\x02 \x01(\v2(.elephant.repositorysocket.DocumentStateR\x05stateB/Z-github.com/ttab/elephant-api/repositorysocketb\x06proto3"

var (
	file_repositorysocket_service_proto_rawDescOnce sync.Once
	file_repositorysocket_service_proto_rawDescData []byte
)

func file_repositorysocket_service_proto_rawDescGZIP() []byte {
	file_repositorysocket_service_proto_rawDescOnce.Do(func() {
		file_repositorysocket_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repositorysocket_service_proto_rawDesc), len(file_repositorysocket_service_proto_rawDesc)))
	})
	return file_repositorysocket_service_proto_rawDescData
}

var file_repositorysocket_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_repositorysocket_service_proto_goTypes = []any{
	(*Call)(nil),                       // 0: elephant.repositorysocket.Call
	(*Response)(nil),                   // 1: elephant.repositorysocket.Response
	(*Error)(nil),                      // 2: elephant.repositorysocket.Error
	(*Authenticate)(nil),               // 3: elephant.repositorysocket.Authenticate
	(*GetEventlog)(nil),                // 4: elephant.repositorysocket.GetEventlog
	(*Subsets)(nil),                    // 5: elephant.repositorysocket.Subsets
	(*EventlogResponse)(nil),           // 6: elephant.repositorysocket.EventlogResponse
	(*EventlogItem)(nil),               // 7: elephant.repositorysocket.EventlogItem
	(*CloseEventlog)(nil),              // 8: elephant.repositorysocket.CloseEventlog
	(*GetDocuments)(nil),               // 9: elephant.repositorysocket.GetDocuments
	(*CloseDocumentSet)(nil),           // 10: elephant.repositorysocket.CloseDocumentSet
	(*DocumentBatch)(nil),              // 11: elephant.repositorysocket.DocumentBatch
	(*DocumentState)(nil),              // 12: elephant.repositorysocket.DocumentState
	(*DocumentUpdate)(nil),             // 13: elephant.repositorysocket.DocumentUpdate
	(*DocumentRemoved)(nil),            // 14: elephant.repositorysocket.DocumentRemoved
	(*InclusionBatch)(nil),             // 15: elephant.repositorysocket.InclusionBatch
	(*InclusionDocument)(nil),          // 16: elephant.repositorysocket.InclusionDocument
	nil,                                // 17: elephant.repositorysocket.GetEventlog.TypeSubsetsEntry
	nil,                                // 18: elephant.repositorysocket.GetDocuments.InclusionSubsetsEntry
	(*repository.EventlogItem)(nil),    // 19: elephant.repository.EventlogItem
	(*repository.ExtractedValues)(nil), // 20: elephant.repository.ExtractedValues
	(*repository.Timespan)(nil),        // 21: elephant.repository.Timespan
	(*repository.DocumentFilter)(nil),  // 22: elephant.repository.DocumentFilter
	(*repository.DocumentMeta)(nil),    // 23: elephant.repository.DocumentMeta
	(*newsdoc.Document)(nil),           // 24: newsdoc.Document
}
var file_repositorysocket_service_proto_depIdxs = []int32{
	3,  // 0: elephant.repositorysocket.Call.authenticate:type_name -> elephant.repositorysocket.Authenticate
	9,  // 1: elephant.repositorysocket.Call.get_documents:type_name -> elephant.repositorysocket.GetDocuments
	10, // 2: elephant.repositorysocket.Call.close_document_set:type_name -> elephant.repositorysocket.CloseDocumentSet
	4,  // 3: elephant.repositorysocket.Call.get_eventlog:type_name -> elephant.repositorysocket.GetEventlog
	8,  // 4: elephant.repositorysocket.Call.close_eventlog:type_name -> elephant.repositorysocket.CloseEventlog
	2,  // 5: elephant.repositorysocket.Response.error:type_name -> elephant.repositorysocket.Error
	11, // 6: elephant.repositorysocket.Response.document_batch:type_name -> elephant.repositorysocket.DocumentBatch
	13, // 7: elephant.repositorysocket.Response.document_update:type_name -> elephant.repositorysocket.DocumentUpdate
	15, // 8: elephant.repositorysocket.Response.inclusion_batch:type_name -> elephant.repositorysocket.InclusionBatch
	14, // 9: elephant.repositorysocket.Response.removed:type_name -> elephant.repositorysocket.DocumentRemoved
	6,  // 10: elephant.repositorysocket.Response.events:type_name -> elephant.repositorysocket.EventlogResponse
	17, // 11: elephant.repositorysocket.GetEventlog.type_subsets:type_name -> elephant.repositorysocket.GetEventlog.TypeSubsetsEntry
	7,  // 12: elephant.repositorysocket.EventlogResponse.items:type_name -> elephant.repositorysocket.EventlogItem
	19, // 13: elephant.repositorysocket.EventlogItem.event:type_name -> elephant.repository.EventlogItem
	20, // 14: elephant.repositorysocket.EventlogItem.subset:type_name -> elephant.repository.ExtractedValues
	21, // 15: elephant.repositorysocket.GetDocuments.timespan:type_name -> elephant.repository.Timespan
	22, // 16: elephant.repositorysocket.GetDocuments.filter:type_name -> elephant.repository.DocumentFilter
	18, // 17: elephant.repositorysocket.GetDocuments.inclusion_subsets:type_name -> elephant.repositorysocket.GetDocuments.InclusionSubsetsEntry
	12, // 18: elephant.repositorysocket.DocumentBatch.documents:type_name -> elephant.repositorysocket.DocumentState
	23, // 19: elephant.repositorysocket.DocumentState.meta:type_name -> elephant.repository.DocumentMeta
	24, // 20: elephant.repositorysocket.DocumentState.document:type_name -> newsdoc.Document
	20, // 21: elephant.repositorysocket.DocumentState.subset:type_name -> elephant.repository.ExtractedValues
	19, // 22: elephant.repositorysocket.DocumentUpdate.event:type_name -> elephant.repository.EventlogItem
	23, // 23: elephant.repositorysocket.DocumentUpdate.meta:type_name -> elephant.repository.DocumentMeta
	24, // 24: elephant.repositorysocket.DocumentUpdate.document:type_name -> newsdoc.Document
	20, // 25: elephant.repositorysocket.DocumentUpdate.subset:type_name -> elephant.repository.ExtractedValues
	16, // 26: elephant.repositorysocket.InclusionBatch.documents:type_name -> elephant.repositorysocket.InclusionDocument
	12, // 27: elephant.repositorysocket.InclusionDocument.state:type_name -> elephant.repositorysocket.DocumentState
	5,  // 28: elephant.repositorysocket.GetEventlog.TypeSubsetsEntry.value:type_name -> elephant.repositorysocket.Subsets
	5,  // 29: elephant.repositorysocket.GetDocuments.InclusionSubsetsEntry.value:type_name -> elephant.repositorysocket.Subsets
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_repositorysocket_service_proto_init() }
func file_repositorysocket_service_proto_init() {
	if File_repositorysocket_service_proto != nil {
		return
	}
	file_repositorysocket_service_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repositorysocket_service_proto_rawDesc), len(file_repositorysocket_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_repositorysocket_service_proto_goTypes,
		DependencyIndexes: file_repositorysocket_service_proto_depIdxs,
		MessageInfos:      file_repositorysocket_service_proto_msgTypes,
	}.Build()
	File_repositorysocket_service_proto = out.File
	file_repositorysocket_service_proto_goTypes = nil
	file_repositorysocket_service_proto_depIdxs = nil
}
