// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: newsdoc/newsdoc.proto

package newsdoc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document is a NewsDoc document.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID is a unique ID for the document, this can for example be a
	// random v4 UUID, or a URI-derived v5 UUID.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Type is the content type of the document.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// URI identifies the document (in a more human-readable way than the
	// UUID).
	Uri string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	// URL is the browseable location of the document (if any).
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// Title is the title of the document, can be used as the document name,
	// or the headline when the document is displayed.
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// Content is the content of the document, this is essentially what gets
	// rendered on the page when you view a document.
	Content []*Block `protobuf:"bytes,6,rep,name=content,proto3" json:"content,omitempty"`
	// Meta is the metadata for a document, this could be things like
	// teasers, open graph data, newsvalues.
	Meta []*Block `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty"`
	// Links are links to other resources and entities. This could be links
	// to topics, categories and subjects for the document, or credited
	// authors.
	Links []*Block `protobuf:"bytes,8,rep,name=links,proto3" json:"links,omitempty"`
	// Language is the language used in the document as an IETF language
	// tag. F.ex. "en", "en-UK", "es", or "sv-SE".
	Language      string `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_newsdoc_newsdoc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_newsdoc_newsdoc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_newsdoc_newsdoc_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Document) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Document) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Document) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetContent() []*Block {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Document) GetMeta() []*Block {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Document) GetLinks() []*Block {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Document) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

// Block is the building block for data embedded in documents. It is used for
// both content, links and metadata. Blocks have can be nested, but that's
// nothing to strive for, keep it simple.
type Block struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is the block ID,
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// UUID is used to reference another Document in a block.
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// URI is used to reference another entity in a document.
	Uri string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	// URL is a browseable URL for the the block.
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// Type is the type of the block
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	// Title is the title/headline of the block, typically used in the
	// presentation of the block.
	Title string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	// Data contains block data.
	Data map[string]string `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Rel describes the relationship to the document/parent entity.
	Rel string `protobuf:"bytes,8,opt,name=rel,proto3" json:"rel,omitempty"`
	// Role is used either as an alternative to rel, or for nuancing the
	// relationship.
	Role string `protobuf:"bytes,9,opt,name=role,proto3" json:"role,omitempty"`
	// Name is a name for the block. An alternative to "rel" when
	// relationship is a term that doesn't fit.
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	// Value is a value for the block. Useful when we want to store a
	// primitive value.
	Value string `protobuf:"bytes,11,opt,name=value,proto3" json:"value,omitempty"`
	// ContentType is used to describe the content type of the block/linked
	// entity if it differs from the type of the block.
	Contenttype string `protobuf:"bytes,12,opt,name=contenttype,proto3" json:"contenttype,omitempty"`
	// Links are used to link to other resources and documents.
	Links []*Block `protobuf:"bytes,13,rep,name=links,proto3" json:"links,omitempty"`
	// Content is used to embed content blocks.
	Content []*Block `protobuf:"bytes,14,rep,name=content,proto3" json:"content,omitempty"`
	// Meta is used to embed metadata
	Meta []*Block `protobuf:"bytes,15,rep,name=meta,proto3" json:"meta,omitempty"`
	// Sensitivity can be use to communicate how the information in a block
	// can be handled. It could f.ex. be set to "internal", to show that it
	// contains information that must be removed or transformed before
	// publishing.
	Sensitivity   string `protobuf:"bytes,16,opt,name=sensitivity,proto3" json:"sensitivity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_newsdoc_newsdoc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_newsdoc_newsdoc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_newsdoc_newsdoc_proto_rawDescGZIP(), []int{1}
}

func (x *Block) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Block) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Block) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Block) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Block) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Block) GetRel() string {
	if x != nil {
		return x.Rel
	}
	return ""
}

func (x *Block) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Block) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Block) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Block) GetContenttype() string {
	if x != nil {
		return x.Contenttype
	}
	return ""
}

func (x *Block) GetLinks() []*Block {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Block) GetContent() []*Block {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Block) GetMeta() []*Block {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Block) GetSensitivity() string {
	if x != nil {
		return x.Sensitivity
	}
	return ""
}

var File_newsdoc_newsdoc_proto protoreflect.FileDescriptor

const file_newsdoc_newsdoc_proto_rawDesc = "" +
	"\n" +
	"\x15newsdoc/newsdoc.proto\x12\anewsdoc\"\xfc\x01\n" +
	"\bDocument\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12(\n" +
	"\acontent\x18\x06 \x03(\v2\x0e.newsdoc.BlockR\acontent\x12\"\n" +
	"\x04meta\x18\a \x03(\v2\x0e.newsdoc.BlockR\x04meta\x12$\n" +
	"\x05links\x18\b \x03(\v2\x0e.newsdoc.BlockR\x05links\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\"\xe8\x03\n" +
	"\x05Block\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12,\n" +
	"\x04data\x18\a \x03(\v2\x18.newsdoc.Block.DataEntryR\x04data\x12\x10\n" +
	"\x03rel\x18\b \x01(\tR\x03rel\x12\x12\n" +
	"\x04role\x18\t \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\n" +
	" \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\v \x01(\tR\x05value\x12 \n" +
	"\vcontenttype\x18\f \x01(\tR\vcontenttype\x12$\n" +
	"\x05links\x18\r \x03(\v2\x0e.newsdoc.BlockR\x05links\x12(\n" +
	"\acontent\x18\x0e \x03(\v2\x0e.newsdoc.BlockR\acontent\x12\"\n" +
	"\x04meta\x18\x0f \x03(\v2\x0e.newsdoc.BlockR\x04meta\x12 \n" +
	"\vsensitivity\x18\x10 \x01(\tR\vsensitivity\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B&Z$github.com/ttab/elephant-api/newsdocb\x06proto3"

var (
	file_newsdoc_newsdoc_proto_rawDescOnce sync.Once
	file_newsdoc_newsdoc_proto_rawDescData []byte
)

func file_newsdoc_newsdoc_proto_rawDescGZIP() []byte {
	file_newsdoc_newsdoc_proto_rawDescOnce.Do(func() {
		file_newsdoc_newsdoc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_newsdoc_newsdoc_proto_rawDesc), len(file_newsdoc_newsdoc_proto_rawDesc)))
	})
	return file_newsdoc_newsdoc_proto_rawDescData
}

var file_newsdoc_newsdoc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_newsdoc_newsdoc_proto_goTypes = []any{
	(*Document)(nil), // 0: newsdoc.Document
	(*Block)(nil),    // 1: newsdoc.Block
	nil,              // 2: newsdoc.Block.DataEntry
}
var file_newsdoc_newsdoc_proto_depIdxs = []int32{
	1, // 0: newsdoc.Document.content:type_name -> newsdoc.Block
	1, // 1: newsdoc.Document.meta:type_name -> newsdoc.Block
	1, // 2: newsdoc.Document.links:type_name -> newsdoc.Block
	2, // 3: newsdoc.Block.data:type_name -> newsdoc.Block.DataEntry
	1, // 4: newsdoc.Block.links:type_name -> newsdoc.Block
	1, // 5: newsdoc.Block.content:type_name -> newsdoc.Block
	1, // 6: newsdoc.Block.meta:type_name -> newsdoc.Block
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_newsdoc_newsdoc_proto_init() }
func file_newsdoc_newsdoc_proto_init() {
	if File_newsdoc_newsdoc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_newsdoc_newsdoc_proto_rawDesc), len(file_newsdoc_newsdoc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_newsdoc_newsdoc_proto_goTypes,
		DependencyIndexes: file_newsdoc_newsdoc_proto_depIdxs,
		MessageInfos:      file_newsdoc_newsdoc_proto_msgTypes,
	}.Build()
	File_newsdoc_newsdoc_proto = out.File
	file_newsdoc_newsdoc_proto_goTypes = nil
	file_newsdoc_newsdoc_proto_depIdxs = nil
}
