// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v4.24.4
// source: replicant/service.proto

package replicant

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDocumentRequest) Reset() {
	*x = SendDocumentRequest{}
	mi := &file_replicant_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDocumentRequest) ProtoMessage() {}

func (x *SendDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_replicant_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDocumentRequest.ProtoReflect.Descriptor instead.
func (*SendDocumentRequest) Descriptor() ([]byte, []int) {
	return file_replicant_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendDocumentRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SendDocumentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type SendDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetVersion int64                  `protobuf:"varint,1,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendDocumentResponse) Reset() {
	*x = SendDocumentResponse{}
	mi := &file_replicant_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendDocumentResponse) ProtoMessage() {}

func (x *SendDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_replicant_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendDocumentResponse.ProtoReflect.Descriptor instead.
func (*SendDocumentResponse) Descriptor() ([]byte, []int) {
	return file_replicant_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendDocumentResponse) GetTargetVersion() int64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

var File_replicant_service_proto protoreflect.FileDescriptor

var file_replicant_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x65, 0x6c, 0x65, 0x70, 0x68,
	0x61, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x22, 0x3f, 0x0a,
	0x13, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0x3d,
	0x0a, 0x14, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x32, 0x70, 0x0a,
	0x0b, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x61, 0x0a, 0x0c,
	0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x2e, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e,
	0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74,
	0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x44,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x74,
	0x61, 0x62, 0x2f, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x61, 0x6e, 0x74, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_replicant_service_proto_rawDescOnce sync.Once
	file_replicant_service_proto_rawDescData = file_replicant_service_proto_rawDesc
)

func file_replicant_service_proto_rawDescGZIP() []byte {
	file_replicant_service_proto_rawDescOnce.Do(func() {
		file_replicant_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_replicant_service_proto_rawDescData)
	})
	return file_replicant_service_proto_rawDescData
}

var file_replicant_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_replicant_service_proto_goTypes = []any{
	(*SendDocumentRequest)(nil),  // 0: elephant.replicant.SendDocumentRequest
	(*SendDocumentResponse)(nil), // 1: elephant.replicant.SendDocumentResponse
}
var file_replicant_service_proto_depIdxs = []int32{
	0, // 0: elephant.replicant.Replication.SendDocument:input_type -> elephant.replicant.SendDocumentRequest
	1, // 1: elephant.replicant.Replication.SendDocument:output_type -> elephant.replicant.SendDocumentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_replicant_service_proto_init() }
func file_replicant_service_proto_init() {
	if File_replicant_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_replicant_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_replicant_service_proto_goTypes,
		DependencyIndexes: file_replicant_service_proto_depIdxs,
		MessageInfos:      file_replicant_service_proto_msgTypes,
	}.Build()
	File_replicant_service_proto = out.File
	file_replicant_service_proto_rawDesc = nil
	file_replicant_service_proto_goTypes = nil
	file_replicant_service_proto_depIdxs = nil
}
