// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: replicant/service.proto

package replicantconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	replicant "github.com/ttab/elephant-api/replicant"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ReplicationName is the fully-qualified name of the Replication service.
	ReplicationName = "elephant.replicant.Replication"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ReplicationSendDocumentProcedure is the fully-qualified name of the Replication's SendDocument
	// RPC.
	ReplicationSendDocumentProcedure = "/elephant.replicant.Replication/SendDocument"
	// ReplicationConfigureTargetProcedure is the fully-qualified name of the Replication's
	// ConfigureTarget RPC.
	ReplicationConfigureTargetProcedure = "/elephant.replicant.Replication/ConfigureTarget"
	// ReplicationRemoveTargetProcedure is the fully-qualified name of the Replication's RemoveTarget
	// RPC.
	ReplicationRemoveTargetProcedure = "/elephant.replicant.Replication/RemoveTarget"
	// ReplicationChangeTargetStateProcedure is the fully-qualified name of the Replication's
	// ChangeTargetState RPC.
	ReplicationChangeTargetStateProcedure = "/elephant.replicant.Replication/ChangeTargetState"
	// ReplicationGetTargetStateProcedure is the fully-qualified name of the Replication's
	// GetTargetState RPC.
	ReplicationGetTargetStateProcedure = "/elephant.replicant.Replication/GetTargetState"
	// ReplicationListTargetsProcedure is the fully-qualified name of the Replication's ListTargets RPC.
	ReplicationListTargetsProcedure = "/elephant.replicant.Replication/ListTargets"
)

// ReplicationClient is a client for the elephant.replicant.Replication service.
type ReplicationClient interface {
	// SendDocument triggers replication of a single document by UUID.
	SendDocument(context.Context, *connect.Request[replicant.SendDocumentRequest]) (*connect.Response[replicant.SendDocumentResponse], error)
	// ConfigureTarget creates or updates a replication target. The configuration
	// maps to the environment variables used for static configuration in
	// elephant-replicant.
	ConfigureTarget(context.Context, *connect.Request[replicant.ConfigureTargetRequest]) (*connect.Response[replicant.ConfigureTargetResponse], error)
	// RemoveTarget deletes a replication target and stops its replication.
	RemoveTarget(context.Context, *connect.Request[replicant.RemoveTargetRequest]) (*connect.Response[replicant.RemoveTargetResponse], error)
	// ChangeTargetState starts or stops a replication target.
	ChangeTargetState(context.Context, *connect.Request[replicant.ChangeTargetStateRequest]) (*connect.Response[replicant.ChangeTargetStateResponse], error)
	// GetTargetState returns the current state of a replication target.
	GetTargetState(context.Context, *connect.Request[replicant.GetTargetStateRequest]) (*connect.Response[replicant.GetTargetStateResponse], error)
	// ListTargets returns all configured replication targets and their current
	// state.
	ListTargets(context.Context, *connect.Request[replicant.ListTargetsRequest]) (*connect.Response[replicant.ListTargetsResponse], error)
}

// NewReplicationClient constructs a client for the elephant.replicant.Replication service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewReplicationClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ReplicationClient {
	baseURL = strings.TrimRight(baseURL, "/")
	replicationMethods := replicant.File_replicant_service_proto.Services().ByName("Replication").Methods()
	return &replicationClient{
		sendDocument: connect.NewClient[replicant.SendDocumentRequest, replicant.SendDocumentResponse](
			httpClient,
			baseURL+ReplicationSendDocumentProcedure,
			connect.WithSchema(replicationMethods.ByName("SendDocument")),
			connect.WithClientOptions(opts...),
		),
		configureTarget: connect.NewClient[replicant.ConfigureTargetRequest, replicant.ConfigureTargetResponse](
			httpClient,
			baseURL+ReplicationConfigureTargetProcedure,
			connect.WithSchema(replicationMethods.ByName("ConfigureTarget")),
			connect.WithClientOptions(opts...),
		),
		removeTarget: connect.NewClient[replicant.RemoveTargetRequest, replicant.RemoveTargetResponse](
			httpClient,
			baseURL+ReplicationRemoveTargetProcedure,
			connect.WithSchema(replicationMethods.ByName("RemoveTarget")),
			connect.WithClientOptions(opts...),
		),
		changeTargetState: connect.NewClient[replicant.ChangeTargetStateRequest, replicant.ChangeTargetStateResponse](
			httpClient,
			baseURL+ReplicationChangeTargetStateProcedure,
			connect.WithSchema(replicationMethods.ByName("ChangeTargetState")),
			connect.WithClientOptions(opts...),
		),
		getTargetState: connect.NewClient[replicant.GetTargetStateRequest, replicant.GetTargetStateResponse](
			httpClient,
			baseURL+ReplicationGetTargetStateProcedure,
			connect.WithSchema(replicationMethods.ByName("GetTargetState")),
			connect.WithClientOptions(opts...),
		),
		listTargets: connect.NewClient[replicant.ListTargetsRequest, replicant.ListTargetsResponse](
			httpClient,
			baseURL+ReplicationListTargetsProcedure,
			connect.WithSchema(replicationMethods.ByName("ListTargets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// replicationClient implements ReplicationClient.
type replicationClient struct {
	sendDocument      *connect.Client[replicant.SendDocumentRequest, replicant.SendDocumentResponse]
	configureTarget   *connect.Client[replicant.ConfigureTargetRequest, replicant.ConfigureTargetResponse]
	removeTarget      *connect.Client[replicant.RemoveTargetRequest, replicant.RemoveTargetResponse]
	changeTargetState *connect.Client[replicant.ChangeTargetStateRequest, replicant.ChangeTargetStateResponse]
	getTargetState    *connect.Client[replicant.GetTargetStateRequest, replicant.GetTargetStateResponse]
	listTargets       *connect.Client[replicant.ListTargetsRequest, replicant.ListTargetsResponse]
}

// SendDocument calls elephant.replicant.Replication.SendDocument.
func (c *replicationClient) SendDocument(ctx context.Context, req *connect.Request[replicant.SendDocumentRequest]) (*connect.Response[replicant.SendDocumentResponse], error) {
	return c.sendDocument.CallUnary(ctx, req)
}

// ConfigureTarget calls elephant.replicant.Replication.ConfigureTarget.
func (c *replicationClient) ConfigureTarget(ctx context.Context, req *connect.Request[replicant.ConfigureTargetRequest]) (*connect.Response[replicant.ConfigureTargetResponse], error) {
	return c.configureTarget.CallUnary(ctx, req)
}

// RemoveTarget calls elephant.replicant.Replication.RemoveTarget.
func (c *replicationClient) RemoveTarget(ctx context.Context, req *connect.Request[replicant.RemoveTargetRequest]) (*connect.Response[replicant.RemoveTargetResponse], error) {
	return c.removeTarget.CallUnary(ctx, req)
}

// ChangeTargetState calls elephant.replicant.Replication.ChangeTargetState.
func (c *replicationClient) ChangeTargetState(ctx context.Context, req *connect.Request[replicant.ChangeTargetStateRequest]) (*connect.Response[replicant.ChangeTargetStateResponse], error) {
	return c.changeTargetState.CallUnary(ctx, req)
}

// GetTargetState calls elephant.replicant.Replication.GetTargetState.
func (c *replicationClient) GetTargetState(ctx context.Context, req *connect.Request[replicant.GetTargetStateRequest]) (*connect.Response[replicant.GetTargetStateResponse], error) {
	return c.getTargetState.CallUnary(ctx, req)
}

// ListTargets calls elephant.replicant.Replication.ListTargets.
func (c *replicationClient) ListTargets(ctx context.Context, req *connect.Request[replicant.ListTargetsRequest]) (*connect.Response[replicant.ListTargetsResponse], error) {
	return c.listTargets.CallUnary(ctx, req)
}

// ReplicationHandler is an implementation of the elephant.replicant.Replication service.
type ReplicationHandler interface {
	// SendDocument triggers replication of a single document by UUID.
	SendDocument(context.Context, *connect.Request[replicant.SendDocumentRequest]) (*connect.Response[replicant.SendDocumentResponse], error)
	// ConfigureTarget creates or updates a replication target. The configuration
	// maps to the environment variables used for static configuration in
	// elephant-replicant.
	ConfigureTarget(context.Context, *connect.Request[replicant.ConfigureTargetRequest]) (*connect.Response[replicant.ConfigureTargetResponse], error)
	// RemoveTarget deletes a replication target and stops its replication.
	RemoveTarget(context.Context, *connect.Request[replicant.RemoveTargetRequest]) (*connect.Response[replicant.RemoveTargetResponse], error)
	// ChangeTargetState starts or stops a replication target.
	ChangeTargetState(context.Context, *connect.Request[replicant.ChangeTargetStateRequest]) (*connect.Response[replicant.ChangeTargetStateResponse], error)
	// GetTargetState returns the current state of a replication target.
	GetTargetState(context.Context, *connect.Request[replicant.GetTargetStateRequest]) (*connect.Response[replicant.GetTargetStateResponse], error)
	// ListTargets returns all configured replication targets and their current
	// state.
	ListTargets(context.Context, *connect.Request[replicant.ListTargetsRequest]) (*connect.Response[replicant.ListTargetsResponse], error)
}

// NewReplicationHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewReplicationHandler(svc ReplicationHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	replicationMethods := replicant.File_replicant_service_proto.Services().ByName("Replication").Methods()
	replicationSendDocumentHandler := connect.NewUnaryHandler(
		ReplicationSendDocumentProcedure,
		svc.SendDocument,
		connect.WithSchema(replicationMethods.ByName("SendDocument")),
		connect.WithHandlerOptions(opts...),
	)
	replicationConfigureTargetHandler := connect.NewUnaryHandler(
		ReplicationConfigureTargetProcedure,
		svc.ConfigureTarget,
		connect.WithSchema(replicationMethods.ByName("ConfigureTarget")),
		connect.WithHandlerOptions(opts...),
	)
	replicationRemoveTargetHandler := connect.NewUnaryHandler(
		ReplicationRemoveTargetProcedure,
		svc.RemoveTarget,
		connect.WithSchema(replicationMethods.ByName("RemoveTarget")),
		connect.WithHandlerOptions(opts...),
	)
	replicationChangeTargetStateHandler := connect.NewUnaryHandler(
		ReplicationChangeTargetStateProcedure,
		svc.ChangeTargetState,
		connect.WithSchema(replicationMethods.ByName("ChangeTargetState")),
		connect.WithHandlerOptions(opts...),
	)
	replicationGetTargetStateHandler := connect.NewUnaryHandler(
		ReplicationGetTargetStateProcedure,
		svc.GetTargetState,
		connect.WithSchema(replicationMethods.ByName("GetTargetState")),
		connect.WithHandlerOptions(opts...),
	)
	replicationListTargetsHandler := connect.NewUnaryHandler(
		ReplicationListTargetsProcedure,
		svc.ListTargets,
		connect.WithSchema(replicationMethods.ByName("ListTargets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/elephant.replicant.Replication/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ReplicationSendDocumentProcedure:
			replicationSendDocumentHandler.ServeHTTP(w, r)
		case ReplicationConfigureTargetProcedure:
			replicationConfigureTargetHandler.ServeHTTP(w, r)
		case ReplicationRemoveTargetProcedure:
			replicationRemoveTargetHandler.ServeHTTP(w, r)
		case ReplicationChangeTargetStateProcedure:
			replicationChangeTargetStateHandler.ServeHTTP(w, r)
		case ReplicationGetTargetStateProcedure:
			replicationGetTargetStateHandler.ServeHTTP(w, r)
		case ReplicationListTargetsProcedure:
			replicationListTargetsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedReplicationHandler returns CodeUnimplemented from all methods.
type UnimplementedReplicationHandler struct{}

func (UnimplementedReplicationHandler) SendDocument(context.Context, *connect.Request[replicant.SendDocumentRequest]) (*connect.Response[replicant.SendDocumentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.replicant.Replication.SendDocument is not implemented"))
}

func (UnimplementedReplicationHandler) ConfigureTarget(context.Context, *connect.Request[replicant.ConfigureTargetRequest]) (*connect.Response[replicant.ConfigureTargetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.replicant.Replication.ConfigureTarget is not implemented"))
}

func (UnimplementedReplicationHandler) RemoveTarget(context.Context, *connect.Request[replicant.RemoveTargetRequest]) (*connect.Response[replicant.RemoveTargetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.replicant.Replication.RemoveTarget is not implemented"))
}

func (UnimplementedReplicationHandler) ChangeTargetState(context.Context, *connect.Request[replicant.ChangeTargetStateRequest]) (*connect.Response[replicant.ChangeTargetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.replicant.Replication.ChangeTargetState is not implemented"))
}

func (UnimplementedReplicationHandler) GetTargetState(context.Context, *connect.Request[replicant.GetTargetStateRequest]) (*connect.Response[replicant.GetTargetStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.replicant.Replication.GetTargetState is not implemented"))
}

func (UnimplementedReplicationHandler) ListTargets(context.Context, *connect.Request[replicant.ListTargetsRequest]) (*connect.Response[replicant.ListTargetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("elephant.replicant.Replication.ListTargets is not implemented"))
}
